
/* File generated by gen_cfile.py. Should not be modified. */

#include "2088C.h"

/**************************************************************************/
/* Declaration of mapped variables                                        */
/**************************************************************************/
UNS8 Type_Code_of_CAN_2000C_Module_Type_Code_of_PO_ch0 = 0x0;		/* Mapped at index 0x2004, subindex 0x01 */
UNS8 Type_Code_of_CAN_2000C_Module_Type_Code_of_PO_ch1 = 0x0;		/* Mapped at index 0x2004, subindex 0x02 */
UNS8 Type_Code_of_CAN_2000C_Module_Type_Code_of_PO_ch2 = 0x0;		/* Mapped at index 0x2004, subindex 0x03 */
UNS8 Type_Code_of_CAN_2000C_Module_Type_Code_of_PO_ch3 = 0x0;		/* Mapped at index 0x2004, subindex 0x04 */
UNS8 Type_Code_of_CAN_2000C_Module_Type_Code_of_PO_ch4 = 0x0;		/* Mapped at index 0x2004, subindex 0x05 */
UNS8 Type_Code_of_CAN_2000C_Module_Type_Code_of_PO_ch5 = 0x0;		/* Mapped at index 0x2004, subindex 0x06 */
UNS8 Type_Code_of_CAN_2000C_Module_Type_Code_of_PO_ch6 = 0x0;		/* Mapped at index 0x2004, subindex 0x07 */
UNS8 Type_Code_of_CAN_2000C_Module_Type_Code_of_PO_ch7 = 0x0;		/* Mapped at index 0x2004, subindex 0x08 */
UNS32 Read_High_Speed_Counter_High_Speed_Counter_ch0 = 0x0;		/* Mapped at index 0x3000, subindex 0x01 */
UNS32 Read_High_Speed_Counter_High_Speed_Counter_ch1 = 0x0;		/* Mapped at index 0x3000, subindex 0x02 */
UNS32 Read_High_Speed_Counter_High_Speed_Counter_ch2 = 0x0;		/* Mapped at index 0x3000, subindex 0x03 */
UNS32 Read_High_Speed_Counter_High_Speed_Counter_ch3 = 0x0;		/* Mapped at index 0x3000, subindex 0x04 */
UNS32 Read_High_Speed_Counter_High_Speed_Counter_ch4 = 0x0;		/* Mapped at index 0x3000, subindex 0x05 */
UNS32 Read_High_Speed_Counter_High_Speed_Counter_ch5 = 0x0;		/* Mapped at index 0x3000, subindex 0x06 */
UNS32 Read_High_Speed_Counter_High_Speed_Counter_ch6 = 0x0;		/* Mapped at index 0x3000, subindex 0x07 */
UNS32 Read_High_Speed_Counter_High_Speed_Counter_ch7 = 0x0;		/* Mapped at index 0x3000, subindex 0x08 */
UNS8 Clear_Counter_Clear_Counter_ch0 = 0x0;		/* Mapped at index 0x3002, subindex 0x01 */
UNS8 Clear_Counter_Clear_Counter_ch1 = 0x0;		/* Mapped at index 0x3002, subindex 0x02 */
UNS8 Clear_Counter_Clear_Counter_ch2 = 0x0;		/* Mapped at index 0x3002, subindex 0x03 */
UNS8 Clear_Counter_Clear_Counter_ch3 = 0x0;		/* Mapped at index 0x3002, subindex 0x04 */
UNS8 Clear_Counter_Clear_Counter_ch4 = 0x0;		/* Mapped at index 0x3002, subindex 0x05 */
UNS8 Clear_Counter_Clear_Counter_ch5 = 0x0;		/* Mapped at index 0x3002, subindex 0x06 */
UNS8 Clear_Counter_Clear_Counter_ch6 = 0x0;		/* Mapped at index 0x3002, subindex 0x07 */
UNS8 Clear_Counter_Clear_Counter_ch7 = 0x0;		/* Mapped at index 0x3002, subindex 0x08 */
UNS8 Pulse_Output_Start_Pulse_Outputs_ch0 = 0x0;		/* Mapped at index 0x3100, subindex 0x01 */
UNS8 Pulse_Output_Start_Pulse_Outputs_ch1 = 0x0;		/* Mapped at index 0x3100, subindex 0x02 */
UNS8 Pulse_Output_Start_Pulse_Outputs_ch2 = 0x0;		/* Mapped at index 0x3100, subindex 0x03 */
UNS8 Pulse_Output_Start_Pulse_Outputs_ch3 = 0x0;		/* Mapped at index 0x3100, subindex 0x04 */
UNS8 Pulse_Output_Start_Pulse_Outputs_ch4 = 0x0;		/* Mapped at index 0x3100, subindex 0x05 */
UNS8 Pulse_Output_Start_Pulse_Outputs_ch5 = 0x0;		/* Mapped at index 0x3100, subindex 0x06 */
UNS8 Pulse_Output_Start_Pulse_Outputs_ch6 = 0x0;		/* Mapped at index 0x3100, subindex 0x07 */
UNS8 Pulse_Output_Start_Pulse_Outputs_ch7 = 0x0;		/* Mapped at index 0x3100, subindex 0x08 */
UNS16 Set_Burst_Count_16_Bit_Burst_Count_ch0 = 0x0;		/* Mapped at index 0x3101, subindex 0x01 */
UNS16 Set_Burst_Count_16_Bit_Burst_Count_ch1 = 0x0;		/* Mapped at index 0x3101, subindex 0x02 */
UNS16 Set_Burst_Count_16_Bit_Burst_Count_ch2 = 0x0;		/* Mapped at index 0x3101, subindex 0x03 */
UNS16 Set_Burst_Count_16_Bit_Burst_Count_ch3 = 0x0;		/* Mapped at index 0x3101, subindex 0x04 */
UNS16 Set_Burst_Count_16_Bit_Burst_Count_ch4 = 0x0;		/* Mapped at index 0x3101, subindex 0x05 */
UNS16 Set_Burst_Count_16_Bit_Burst_Count_ch5 = 0x0;		/* Mapped at index 0x3101, subindex 0x06 */
UNS16 Set_Burst_Count_16_Bit_Burst_Count_ch6 = 0x0;		/* Mapped at index 0x3101, subindex 0x07 */
UNS16 Set_Burst_Count_16_Bit_Burst_Count_ch7 = 0x0;		/* Mapped at index 0x3101, subindex 0x08 */
UNS32 Set_Pulse_Frequency_32_Bit_Pulse_Frequency_ch0 = 0x2;		/* Mapped at index 0x3102, subindex 0x01 */
UNS32 Set_Pulse_Frequency_32_Bit_Pulse_Frequency_ch1 = 0x2;		/* Mapped at index 0x3102, subindex 0x02 */
UNS32 Set_Pulse_Frequency_32_Bit_Pulse_Frequency_ch2 = 0x2;		/* Mapped at index 0x3102, subindex 0x03 */
UNS32 Set_Pulse_Frequency_32_Bit_Pulse_Frequency_ch3 = 0x2;		/* Mapped at index 0x3102, subindex 0x04 */
UNS32 Set_Pulse_Frequency_32_Bit_Pulse_Frequency_ch4 = 0x2;		/* Mapped at index 0x3102, subindex 0x05 */
UNS32 Set_Pulse_Frequency_32_Bit_Pulse_Frequency_ch5 = 0x2;		/* Mapped at index 0x3102, subindex 0x06 */
UNS32 Set_Pulse_Frequency_32_Bit_Pulse_Frequency_ch6 = 0x2;		/* Mapped at index 0x3102, subindex 0x07 */
UNS32 Set_Pulse_Frequency_32_Bit_Pulse_Frequency_ch7 = 0x2;		/* Mapped at index 0x3102, subindex 0x08 */
UNS16 Set_Pulse_Duty_16_Bit_Pulse_Duty_ch0 = 0x1F4;		/* Mapped at index 0x3103, subindex 0x01 */
UNS16 Set_Pulse_Duty_16_Bit_Pulse_Duty_ch1 = 0x1F4;		/* Mapped at index 0x3103, subindex 0x02 */
UNS16 Set_Pulse_Duty_16_Bit_Pulse_Duty_ch2 = 0x1F4;		/* Mapped at index 0x3103, subindex 0x03 */
UNS16 Set_Pulse_Duty_16_Bit_Pulse_Duty_ch3 = 0x1F4;		/* Mapped at index 0x3103, subindex 0x04 */
UNS16 Set_Pulse_Duty_16_Bit_Pulse_Duty_ch4 = 0x1F4;		/* Mapped at index 0x3103, subindex 0x05 */
UNS16 Set_Pulse_Duty_16_Bit_Pulse_Duty_ch5 = 0x1F4;		/* Mapped at index 0x3103, subindex 0x06 */
UNS16 Set_Pulse_Duty_16_Bit_Pulse_Duty_ch6 = 0x1F4;		/* Mapped at index 0x3103, subindex 0x07 */
UNS16 Set_Pulse_Duty_16_Bit_Pulse_Duty_ch7 = 0x1F4;		/* Mapped at index 0x3103, subindex 0x08 */
UNS8 Set_Hardware_Trig_8_Bit_Hardware_Trig_ch0 = 0x0;		/* Mapped at index 0x3104, subindex 0x01 */
UNS8 Set_Hardware_Trig_8_Bit_Hardware_Trig_ch1 = 0x0;		/* Mapped at index 0x3104, subindex 0x02 */
UNS8 Set_Hardware_Trig_8_Bit_Hardware_Trig_ch2 = 0x0;		/* Mapped at index 0x3104, subindex 0x03 */
UNS8 Set_Hardware_Trig_8_Bit_Hardware_Trig_ch3 = 0x0;		/* Mapped at index 0x3104, subindex 0x04 */
UNS8 Set_Hardware_Trig_8_Bit_Hardware_Trig_ch4 = 0x0;		/* Mapped at index 0x3104, subindex 0x05 */
UNS8 Set_Hardware_Trig_8_Bit_Hardware_Trig_ch5 = 0x0;		/* Mapped at index 0x3104, subindex 0x06 */
UNS8 Set_Hardware_Trig_8_Bit_Hardware_Trig_ch6 = 0x0;		/* Mapped at index 0x3104, subindex 0x07 */
UNS8 Set_Hardware_Trig_8_Bit_Hardware_Trig_ch7 = 0x0;		/* Mapped at index 0x3104, subindex 0x08 */
UNS8 Set_Sync_Channel_8_Bit_Sync_Channel_ch0 = 0x0;		/* Mapped at index 0x3105, subindex 0x01 */
UNS8 Set_Sync_Channel_8_Bit_Sync_Channel_ch1 = 0x0;		/* Mapped at index 0x3105, subindex 0x02 */
UNS8 Set_Sync_Channel_8_Bit_Sync_Channel_ch2 = 0x0;		/* Mapped at index 0x3105, subindex 0x03 */
UNS8 Set_Sync_Channel_8_Bit_Sync_Channel_ch3 = 0x0;		/* Mapped at index 0x3105, subindex 0x04 */
UNS8 Set_Sync_Channel_8_Bit_Sync_Channel_ch4 = 0x0;		/* Mapped at index 0x3105, subindex 0x05 */
UNS8 Set_Sync_Channel_8_Bit_Sync_Channel_ch5 = 0x0;		/* Mapped at index 0x3105, subindex 0x06 */
UNS8 Set_Sync_Channel_8_Bit_Sync_Channel_ch6 = 0x0;		/* Mapped at index 0x3105, subindex 0x07 */
UNS8 Set_Sync_Channel_8_Bit_Sync_Channel_ch7 = 0x0;		/* Mapped at index 0x3105, subindex 0x08 */
UNS8 Set_Sync_Start_8_Bit_Sync_Start = 0x0;		/* Mapped at index 0x3106, subindex 0x01 */
UNS16 Set_Deceleration_16_Bit_Deceleration_ch0 = 0x0;		/* Mapped at index 0x3110, subindex 0x01 */
UNS16 Set_Deceleration_16_Bit_Deceleration_ch1 = 0x0;		/* Mapped at index 0x3110, subindex 0x02 */
UNS16 Set_Deceleration_16_Bit_Deceleration_ch2 = 0x0;		/* Mapped at index 0x3110, subindex 0x03 */
UNS16 Set_Deceleration_16_Bit_Deceleration_ch3 = 0x0;		/* Mapped at index 0x3110, subindex 0x04 */
UNS16 Set_Deceleration_16_Bit_Deceleration_ch4 = 0x0;		/* Mapped at index 0x3110, subindex 0x05 */
UNS16 Set_Deceleration_16_Bit_Deceleration_ch5 = 0x0;		/* Mapped at index 0x3110, subindex 0x06 */
UNS16 Set_Deceleration_16_Bit_Deceleration_ch6 = 0x0;		/* Mapped at index 0x3110, subindex 0x07 */
UNS16 Set_Deceleration_16_Bit_Deceleration_ch7 = 0x0;		/* Mapped at index 0x3110, subindex 0x08 */
UNS16 Set_Acceleration_16_Bit_Acceleration_ch0 = 0x0;		/* Mapped at index 0x3111, subindex 0x01 */
UNS16 Set_Acceleration_16_Bit_Acceleration_ch1 = 0x0;		/* Mapped at index 0x3111, subindex 0x02 */
UNS16 Set_Acceleration_16_Bit_Acceleration_ch2 = 0x0;		/* Mapped at index 0x3111, subindex 0x03 */
UNS16 Set_Acceleration_16_Bit_Acceleration_ch3 = 0x0;		/* Mapped at index 0x3111, subindex 0x04 */
UNS16 Set_Acceleration_16_Bit_Acceleration_ch4 = 0x0;		/* Mapped at index 0x3111, subindex 0x05 */
UNS16 Set_Acceleration_16_Bit_Acceleration_ch5 = 0x0;		/* Mapped at index 0x3111, subindex 0x06 */
UNS16 Set_Acceleration_16_Bit_Acceleration_ch6 = 0x0;		/* Mapped at index 0x3111, subindex 0x07 */
UNS16 Set_Acceleration_16_Bit_Acceleration_ch7 = 0x0;		/* Mapped at index 0x3111, subindex 0x08 */
UNS8 Set_Channel_Group_8_Bit_Channel_Group_ch0 = 0x0;		/* Mapped at index 0x3112, subindex 0x01 */
UNS8 Set_Channel_Group_8_Bit_Channel_Group_ch1 = 0x0;		/* Mapped at index 0x3112, subindex 0x02 */
UNS8 Set_Channel_Group_8_Bit_Channel_Group_ch2 = 0x0;		/* Mapped at index 0x3112, subindex 0x03 */
UNS8 Set_Channel_Group_8_Bit_Channel_Group_ch3 = 0x0;		/* Mapped at index 0x3112, subindex 0x04 */
UNS8 Set_Channel_Group_8_Bit_Channel_Group_ch4 = 0x0;		/* Mapped at index 0x3112, subindex 0x05 */
UNS8 Set_Channel_Group_8_Bit_Channel_Group_ch5 = 0x0;		/* Mapped at index 0x3112, subindex 0x06 */
UNS8 Set_Channel_Group_8_Bit_Channel_Group_ch6 = 0x0;		/* Mapped at index 0x3112, subindex 0x07 */
UNS8 Set_Channel_Group_8_Bit_Channel_Group_ch7 = 0x0;		/* Mapped at index 0x3112, subindex 0x08 */
UNS8 Read_Inputs_8_Bit[] =		/* Mapped at index 0x6000, subindex 0x01 - 0x01 */
  {
    0x0	/* 0 */
  };

/**************************************************************************/
/* Declaration of value range types                                       */
/**************************************************************************/

#define valueRange_EMC 0x9F /* Type for index 0x1003 subindex 0x00 (only set of value 0 is possible) */
UNS32 _valueRangeTest (UNS8 typeValue, void * value)
{
  switch (typeValue) {
    case valueRange_EMC:
      if (*(UNS8*)value != (UNS8)0) return OD_VALUE_RANGE_EXCEEDED;
      break;
  }
  return 0;
}

/**************************************************************************/
/* The node id                                                            */
/**************************************************************************/
/* node_id default value.*/
UNS8 _bDeviceNodeId = 0x00;

/**************************************************************************/
/* Array of message processing information */

const UNS8 _iam_a_slave = 1;

TIMER_HANDLE _heartBeatTimers[1];

/*
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

                               OBJECT DICTIONARY

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
*/

/* index 0x1000 :   Device Type. */
                    UNS32 _obj1000 = 0x200191;	/* 2097553 */
                    subindex _Index1000[] = 
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&_obj1000 }
                     };

/* index 0x1001 :   Error Register. */
                    UNS8 _obj1001 = 0x0;	/* 0 */
                    subindex _Index1001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&_obj1001 }
                     };

/* index 0x1003 :   Pre-defined Error Field. */
                    UNS8 _highestSubIndex_obj1003 = 0; /* number of subindex - 1*/
                    UNS32 _obj1003[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    ODCallback_t _Index1003_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex _Index1003[] = 
                     {
                       { RW, valueRange_EMC, sizeof (UNS8), (void*)&_highestSubIndex_obj1003 },
                       { RO, uint32, sizeof (UNS32), (void*)&_obj1003[0] },
                       { RO, uint32, sizeof (UNS32), (void*)&_obj1003[1] },
                       { RO, uint32, sizeof (UNS32), (void*)&_obj1003[2] },
                       { RO, uint32, sizeof (UNS32), (void*)&_obj1003[3] },
                       { RO, uint32, sizeof (UNS32), (void*)&_obj1003[4] }
                     };

/* index 0x1005 :   SYNC COB ID. */
                    UNS32 _obj1005 = 0x80;	/* 128 */
                    ODCallback_t _Index1005_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex _Index1005[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1005 }
                     };

/* index 0x1006 :   Communication / Cycle Period */
                    UNS32 _obj1006 = 0x0;   /* 0 */

/* index 0x1008 :   Manufacturer Device Name. */
                    UNS8 _obj1008[10] = "CAN-2088";
                    subindex _Index1008[] = 
                     {
                       { RO, visible_string, 10, (void*)&_obj1008 }
                     };

/* index 0x1009 :   Manufacturer Hardware Version. */
                    UNS8 _obj1009[10] = "1.1";
                    subindex _Index1009[] = 
                     {
                       { RO, visible_string, 10, (void*)&_obj1009 }
                     };

/* index 0x100A :   Manufacturer Software Version. */
                    UNS8 _obj100A[13] = "1.10-20110616";
                    subindex _Index100A[] = 
                     {
                       { RO, visible_string, 13, (void*)&_obj100A }
                     };

/* index 0x100C :   Guard Time. */
                    UNS16 _obj100C = 0x0;	/* 0 */
                    subindex _Index100C[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&_obj100C }
                     };

/* index 0x100D :   Life Time Factor. */
                    UNS8 _obj100D = 0x0;	/* 0 */
                    subindex _Index100D[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&_obj100D }
                     };

/* index 0x1010 :   Store parameters. */
                    UNS8 _highestSubIndex_obj1010 = 1; /* number of subindex - 1*/
                    UNS32 _obj1010_Save_All_Parameters = 0x0;	/* 0 */
                    subindex _Index1010[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj1010 },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1010_Save_All_Parameters }
                     };

/* index 0x1011 :   Restore Default Parameters. */
                    UNS8 _highestSubIndex_obj1011 = 1; /* number of subindex - 1*/
                    UNS32 _obj1011_Restore_All_Default_Parameters = 0x0;	/* 0 */
                    subindex _Index1011[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj1011 },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1011_Restore_All_Default_Parameters }
                     };

/* index 0x1014 :   Emergency COB ID. */
                    UNS32 _obj1014 = 0x80;	/* 128 */
                    subindex _Index1014[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1014 }
                     };

/* index 0x1016 :   Consumer Heartbeat Time */
                    UNS8 _highestSubIndex_obj1016 = 0;
                    UNS32 _obj1016[]={0};

/* index 0x1017 :   Producer Heartbeat Time. */
                    UNS16 _obj1017 = 0x0;	/* 0 */
                    ODCallback_t _Index1017_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex _Index1017[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&_obj1017 }
                     };

/* index 0x1018 :   Identity. */
                    UNS8 _highestSubIndex_obj1018 = 4; /* number of subindex - 1*/
                    UNS32 _obj1018_Vendor_ID = 0x13C;	/* 316 */
                    UNS32 _obj1018_Product_Code = 0x2088;	/* 8328 */
                    UNS32 _obj1018_Revision_Number = 0x20002;	/* 131074 */
                    UNS32 _obj1018_Serial_Number = 0x6CD3683C;	/* 1825794108 */
                    subindex _Index1018[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj1018 },
                       { RO, uint32, sizeof (UNS32), (void*)&_obj1018_Vendor_ID },
                       { RO, uint32, sizeof (UNS32), (void*)&_obj1018_Product_Code },
                       { RO, uint32, sizeof (UNS32), (void*)&_obj1018_Revision_Number },
                       { RO, uint32, sizeof (UNS32), (void*)&_obj1018_Serial_Number }
                     };

/* index 0x1200 :   Server SDO Parameter. */
                    UNS8 _highestSubIndex_obj1200 = 2; /* number of subindex - 1*/
                    UNS32 _obj1200_COB_ID_Client_to_Server_Receive_SDO = 0x600;	/* 1536 */
                    UNS32 _obj1200_COB_ID_Server_to_Client_Transmit_SDO = 0x580;	/* 1408 */
                    subindex _Index1200[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj1200 },
                       { RO, uint32, sizeof (UNS32), (void*)&_obj1200_COB_ID_Client_to_Server_Receive_SDO },
                       { RO, uint32, sizeof (UNS32), (void*)&_obj1200_COB_ID_Server_to_Client_Transmit_SDO }
                     };

/* index 0x1400 :   Receive PDO 1 Parameter. */
                    UNS8 _highestSubIndex_obj1400 = 2; /* number of subindex - 1*/
                    UNS32 _obj1400_COB_ID_used_by_PDO = 0x200;	/* 512 */
                    UNS8 _obj1400_Transmission_Type = 0xFF;	/* 255 */
                    subindex _Index1400[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj1400 },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1400_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&_obj1400_Transmission_Type }
                     };

/* index 0x1401 :   Receive PDO 2 Parameter. */
                    UNS8 _highestSubIndex_obj1401 = 2; /* number of subindex - 1*/
                    UNS32 _obj1401_COB_ID_used_by_PDO = 0x300;	/* 768 */
                    UNS8 _obj1401_Transmission_Type = 0xFF;	/* 255 */
                    subindex _Index1401[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj1401 },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1401_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&_obj1401_Transmission_Type }
                     };

/* index 0x1402 :   Receive PDO 3 Parameter. */
                    UNS8 _highestSubIndex_obj1402 = 2; /* number of subindex - 1*/
                    UNS32 _obj1402_COB_ID_used_by_PDO = 0x400;	/* 1024 */
                    UNS8 _obj1402_Transmission_Type = 0xFF;	/* 255 */
                    subindex _Index1402[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj1402 },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1402_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&_obj1402_Transmission_Type }
                     };

/* index 0x1403 :   Receive PDO 4 Parameter. */
                    UNS8 _highestSubIndex_obj1403 = 2; /* number of subindex - 1*/
                    UNS32 _obj1403_COB_ID_used_by_PDO = 0x500;	/* 1280 */
                    UNS8 _obj1403_Transmission_Type = 0xFF;	/* 255 */
                    subindex _Index1403[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj1403 },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1403_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&_obj1403_Transmission_Type }
                     };

/* index 0x1404 :   Receive PDO 5 Parameter. */
                    UNS8 _highestSubIndex_obj1404 = 2; /* number of subindex - 1*/
                    UNS32 _obj1404_COB_ID_used_by_PDO = 0xC0000000;	/* 3221225472 */
                    UNS8 _obj1404_Transmission_Type = 0xFF;	/* 255 */
                    subindex _Index1404[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj1404 },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1404_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&_obj1404_Transmission_Type }
                     };

/* index 0x1405 :   Receive PDO 6 Parameter. */
                    UNS8 _highestSubIndex_obj1405 = 2; /* number of subindex - 1*/
                    UNS32 _obj1405_COB_ID_used_by_PDO = 0xC0000000;	/* 3221225472 */
                    UNS8 _obj1405_Transmission_Type = 0xFF;	/* 255 */
                    subindex _Index1405[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj1405 },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1405_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&_obj1405_Transmission_Type }
                     };

/* index 0x1406 :   Receive PDO 7 Parameter. */
                    UNS8 _highestSubIndex_obj1406 = 2; /* number of subindex - 1*/
                    UNS32 _obj1406_COB_ID_used_by_PDO = 0xC0000000;	/* 3221225472 */
                    UNS8 _obj1406_Transmission_Type = 0xFF;	/* 255 */
                    subindex _Index1406[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj1406 },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1406_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&_obj1406_Transmission_Type }
                     };

/* index 0x1407 :   Receive PDO 8 Parameter. */
                    UNS8 _highestSubIndex_obj1407 = 2; /* number of subindex - 1*/
                    UNS32 _obj1407_COB_ID_used_by_PDO = 0xC0000000;	/* 3221225472 */
                    UNS8 _obj1407_Transmission_Type = 0xFF;	/* 255 */
                    subindex _Index1407[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj1407 },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1407_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&_obj1407_Transmission_Type }
                     };

/* index 0x1408 :   Receive PDO 9 Parameter. */
                    UNS8 _highestSubIndex_obj1408 = 2; /* number of subindex - 1*/
                    UNS32 _obj1408_COB_ID_used_by_PDO = 0xC0000000;	/* 3221225472 */
                    UNS8 _obj1408_Transmission_Type = 0xFF;	/* 255 */
                    subindex _Index1408[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj1408 },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1408_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&_obj1408_Transmission_Type }
                     };

/* index 0x1409 :   Receive PDO 10 Parameter. */
                    UNS8 _highestSubIndex_obj1409 = 2; /* number of subindex - 1*/
                    UNS32 _obj1409_COB_ID_used_by_PDO = 0xC0000000;	/* 3221225472 */
                    UNS8 _obj1409_Transmission_Type = 0xFF;	/* 255 */
                    subindex _Index1409[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj1409 },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1409_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&_obj1409_Transmission_Type }
                     };

/* index 0x1600 :   Receive PDO 1 Mapping. */
                    UNS8 _highestSubIndex_obj1600 = 8; /* number of subindex - 1*/
                    UNS32 _obj1600[] = 
                    {
                      0x31000108,	/* 822083848 */
                      0x31000208,	/* 822084104 */
                      0x31000308,	/* 822084360 */
                      0x31000408,	/* 822084616 */
                      0x31000508,	/* 822084872 */
                      0x31000608,	/* 822085128 */
                      0x31000708,	/* 822085384 */
                      0x31000808	/* 822085640 */
                    };
                    subindex _Index1600[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj1600 },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1600[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1600[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1600[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1600[3] },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1600[4] },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1600[5] },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1600[6] },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1600[7] }
                     };

/* index 0x1601 :   Receive PDO 2 Mapping. */
                    UNS8 _highestSubIndex_obj1601 = 4; /* number of subindex - 1*/
                    UNS32 _obj1601[] = 
                    {
                      0x31030110,	/* 822280464 */
                      0x31030210,	/* 822280720 */
                      0x31030310,	/* 822280976 */
                      0x31030410	/* 822281232 */
                    };
                    subindex _Index1601[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj1601 },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1601[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1601[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1601[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1601[3] }
                     };

/* index 0x1602 :   Receive PDO 3 Mapping. */
                    UNS8 _highestSubIndex_obj1602 = 4; /* number of subindex - 1*/
                    UNS32 _obj1602[] = 
                    {
                      0x31030510,	/* 822281488 */
                      0x31030610,	/* 822281744 */
                      0x31030710,	/* 822282000 */
                      0x31030810	/* 822282256 */
                    };
                    subindex _Index1602[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj1602 },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1602[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1602[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1602[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1602[3] }
                     };

/* index 0x1603 :   Receive PDO 4 Mapping. */
                    UNS8 _highestSubIndex_obj1603 = 8; /* number of subindex - 1*/
                    UNS32 _obj1603[] = 
                    {
                      0x30020108,	/* 805437704 */
                      0x30020208,	/* 805437960 */
                      0x30020308,	/* 805438216 */
                      0x30020408,	/* 805438472 */
                      0x30020508,	/* 805438728 */
                      0x30020608,	/* 805438984 */
                      0x30020708,	/* 805439240 */
                      0x30020808	/* 805439496 */
                    };
                    subindex _Index1603[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj1603 },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1603[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1603[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1603[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1603[3] },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1603[4] },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1603[5] },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1603[6] },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1603[7] }
                     };

/* index 0x1604 :   Receive PDO 5 Mapping. */
                    UNS8 _highestSubIndex_obj1604 = 0; /* number of subindex - 1*/
                    UNS32 _obj1604[] = 
                    {
                    };
                    subindex _Index1604[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj1604 }
                     };

/* index 0x1605 :   Receive PDO 6 Mapping. */
                    UNS8 _highestSubIndex_obj1605 = 0; /* number of subindex - 1*/
                    UNS32 _obj1605[] = 
                    {
                    };
                    subindex _Index1605[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj1605 }
                     };

/* index 0x1606 :   Receive PDO 7 Mapping. */
                    UNS8 _highestSubIndex_obj1606 = 0; /* number of subindex - 1*/
                    UNS32 _obj1606[] = 
                    {
                    };
                    subindex _Index1606[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj1606 }
                     };

/* index 0x1607 :   Receive PDO 8 Mapping. */
                    UNS8 _highestSubIndex_obj1607 = 0; /* number of subindex - 1*/
                    UNS32 _obj1607[] = 
                    {
                    };
                    subindex _Index1607[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj1607 }
                     };

/* index 0x1608 :   Receive PDO 9 Mapping. */
                    UNS8 _highestSubIndex_obj1608 = 0; /* number of subindex - 1*/
                    UNS32 _obj1608[] = 
                    {
                    };
                    subindex _Index1608[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj1608 }
                     };

/* index 0x1609 :   Receive PDO 10 Mapping. */
                    UNS8 _highestSubIndex_obj1609 = 0; /* number of subindex - 1*/
                    UNS32 _obj1609[] = 
                    {
                    };
                    subindex _Index1609[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj1609 }
                     };

/* index 0x1800 :   Transmit PDO 1 Parameter. */
                    UNS8 _highestSubIndex_obj1800 = 5; /* number of subindex - 1*/
                    UNS32 _obj1800_COB_ID_used_by_PDO = 0x180;	/* 384 */
                    UNS8 _obj1800_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 _obj1800_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 _obj1800_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 _obj1800_Event_Timer = 0x0;	/* 0 */
                    ODCallback_t _Index1800_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex _Index1800[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj1800 },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1800_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&_obj1800_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&_obj1800_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&_obj1800_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&_obj1800_Event_Timer }
                     };

/* index 0x1801 :   Transmit PDO 2 Parameter. */
                    UNS8 _highestSubIndex_obj1801 = 5; /* number of subindex - 1*/
                    UNS32 _obj1801_COB_ID_used_by_PDO = 0x280;	/* 640 */
                    UNS8 _obj1801_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 _obj1801_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 _obj1801_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 _obj1801_Event_Timer = 0x0;	/* 0 */
                    ODCallback_t _Index1801_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex _Index1801[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj1801 },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1801_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&_obj1801_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&_obj1801_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&_obj1801_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&_obj1801_Event_Timer }
                     };

/* index 0x1802 :   Transmit PDO 3 Parameter. */
                    UNS8 _highestSubIndex_obj1802 = 5; /* number of subindex - 1*/
                    UNS32 _obj1802_COB_ID_used_by_PDO = 0x380;	/* 896 */
                    UNS8 _obj1802_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 _obj1802_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 _obj1802_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 _obj1802_Event_Timer = 0x0;	/* 0 */
                    ODCallback_t _Index1802_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex _Index1802[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj1802 },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1802_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&_obj1802_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&_obj1802_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&_obj1802_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&_obj1802_Event_Timer }
                     };

/* index 0x1803 :   Transmit PDO 4 Parameter. */
                    UNS8 _highestSubIndex_obj1803 = 5; /* number of subindex - 1*/
                    UNS32 _obj1803_COB_ID_used_by_PDO = 0x480;	/* 1152 */
                    UNS8 _obj1803_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 _obj1803_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 _obj1803_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 _obj1803_Event_Timer = 0x0;	/* 0 */
                    ODCallback_t _Index1803_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex _Index1803[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj1803 },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1803_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&_obj1803_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&_obj1803_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&_obj1803_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&_obj1803_Event_Timer }
                     };

/* index 0x1804 :   Transmit PDO 5 Parameter. */
                    UNS8 _highestSubIndex_obj1804 = 5; /* number of subindex - 1*/
                    UNS32 _obj1804_COB_ID_used_by_PDO = 0x80000000;	/* 2147483648 */
                    UNS8 _obj1804_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 _obj1804_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 _obj1804_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 _obj1804_Event_Timer = 0x0;	/* 0 */
                    ODCallback_t _Index1804_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex _Index1804[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj1804 },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1804_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&_obj1804_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&_obj1804_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&_obj1804_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&_obj1804_Event_Timer }
                     };

/* index 0x1805 :   Transmit PDO 6 Parameter. */
                    UNS8 _highestSubIndex_obj1805 = 5; /* number of subindex - 1*/
                    UNS32 _obj1805_COB_ID_used_by_PDO = 0x80000000;	/* 2147483648 */
                    UNS8 _obj1805_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 _obj1805_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 _obj1805_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 _obj1805_Event_Timer = 0x0;	/* 0 */
                    ODCallback_t _Index1805_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex _Index1805[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj1805 },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1805_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&_obj1805_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&_obj1805_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&_obj1805_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&_obj1805_Event_Timer }
                     };

/* index 0x1806 :   Transmit PDO 7 Parameter. */
                    UNS8 _highestSubIndex_obj1806 = 5; /* number of subindex - 1*/
                    UNS32 _obj1806_COB_ID_used_by_PDO = 0x80000000;	/* 2147483648 */
                    UNS8 _obj1806_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 _obj1806_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 _obj1806_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 _obj1806_Event_Timer = 0x0;	/* 0 */
                    ODCallback_t _Index1806_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex _Index1806[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj1806 },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1806_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&_obj1806_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&_obj1806_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&_obj1806_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&_obj1806_Event_Timer }
                     };

/* index 0x1807 :   Transmit PDO 8 Parameter. */
                    UNS8 _highestSubIndex_obj1807 = 5; /* number of subindex - 1*/
                    UNS32 _obj1807_COB_ID_used_by_PDO = 0x80000000;	/* 2147483648 */
                    UNS8 _obj1807_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 _obj1807_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 _obj1807_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 _obj1807_Event_Timer = 0x0;	/* 0 */
                    ODCallback_t _Index1807_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex _Index1807[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj1807 },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1807_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&_obj1807_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&_obj1807_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&_obj1807_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&_obj1807_Event_Timer }
                     };

/* index 0x1808 :   Transmit PDO 9 Parameter. */
                    UNS8 _highestSubIndex_obj1808 = 5; /* number of subindex - 1*/
                    UNS32 _obj1808_COB_ID_used_by_PDO = 0x80000000;	/* 2147483648 */
                    UNS8 _obj1808_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 _obj1808_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 _obj1808_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 _obj1808_Event_Timer = 0x0;	/* 0 */
                    ODCallback_t _Index1808_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex _Index1808[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj1808 },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1808_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&_obj1808_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&_obj1808_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&_obj1808_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&_obj1808_Event_Timer }
                     };

/* index 0x1809 :   Transmit PDO 10 Parameter. */
                    UNS8 _highestSubIndex_obj1809 = 5; /* number of subindex - 1*/
                    UNS32 _obj1809_COB_ID_used_by_PDO = 0x80000000;	/* 2147483648 */
                    UNS8 _obj1809_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 _obj1809_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 _obj1809_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 _obj1809_Event_Timer = 0x0;	/* 0 */
                    ODCallback_t _Index1809_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex _Index1809[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj1809 },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1809_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&_obj1809_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&_obj1809_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&_obj1809_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&_obj1809_Event_Timer }
                     };

/* index 0x1A00 :   Transmit PDO 1 Mapping. */
                    UNS8 _highestSubIndex_obj1A00 = 1; /* number of subindex - 1*/
                    UNS32 _obj1A00[] = 
                    {
                      0x60000108	/* 1610613000 */
                    };
                    subindex _Index1A00[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj1A00 },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1A00[0] }
                     };

/* index 0x1A01 :   Transmit PDO 2 Mapping. */
                    UNS8 _highestSubIndex_obj1A01 = 2; /* number of subindex - 1*/
                    UNS32 _obj1A01[] = 
                    {
                      0x30000120,	/* 805306656 */
                      0x30000220	/* 805306912 */
                    };
                    subindex _Index1A01[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj1A01 },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1A01[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1A01[1] }
                     };

/* index 0x1A02 :   Transmit PDO 3 Mapping. */
                    UNS8 _highestSubIndex_obj1A02 = 2; /* number of subindex - 1*/
                    UNS32 _obj1A02[] = 
                    {
                      0x30000320,	/* 805307168 */
                      0x30000420	/* 805307424 */
                    };
                    subindex _Index1A02[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj1A02 },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1A02[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1A02[1] }
                     };

/* index 0x1A03 :   Transmit PDO 4 Mapping. */
                    UNS8 _highestSubIndex_obj1A03 = 2; /* number of subindex - 1*/
                    UNS32 _obj1A03[] = 
                    {
                      0x30000520,	/* 805307680 */
                      0x30000620	/* 805307936 */
                    };
                    subindex _Index1A03[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj1A03 },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1A03[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1A03[1] }
                     };

/* index 0x1A04 :   Transmit PDO 5 Mapping. */
                    UNS8 _highestSubIndex_obj1A04 = 2; /* number of subindex - 1*/
                    UNS32 _obj1A04[] = 
                    {
                      0x30000720,	/* 805308192 */
                      0x30000820	/* 805308448 */
                    };
                    subindex _Index1A04[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj1A04 },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1A04[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1A04[1] }
                     };

/* index 0x1A05 :   Transmit PDO 6 Mapping. */
                    UNS8 _highestSubIndex_obj1A05 = 0; /* number of subindex - 1*/
                    UNS32 _obj1A05[] = 
                    {
                    };
                    subindex _Index1A05[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj1A05 }
                     };

/* index 0x1A06 :   Transmit PDO 7 Mapping. */
                    UNS8 _highestSubIndex_obj1A06 = 0; /* number of subindex - 1*/
                    UNS32 _obj1A06[] = 
                    {
                    };
                    subindex _Index1A06[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj1A06 }
                     };

/* index 0x1A07 :   Transmit PDO 8 Mapping. */
                    UNS8 _highestSubIndex_obj1A07 = 0; /* number of subindex - 1*/
                    UNS32 _obj1A07[] = 
                    {
                    };
                    subindex _Index1A07[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj1A07 }
                     };

/* index 0x1A08 :   Transmit PDO 9 Mapping. */
                    UNS8 _highestSubIndex_obj1A08 = 0; /* number of subindex - 1*/
                    UNS32 _obj1A08[] = 
                    {
                    };
                    subindex _Index1A08[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj1A08 }
                     };

/* index 0x1A09 :   Transmit PDO 10 Mapping. */
                    UNS8 _highestSubIndex_obj1A09 = 0; /* number of subindex - 1*/
                    UNS32 _obj1A09[] = 
                    {
                    };
                    subindex _Index1A09[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj1A09 }
                     };

/* index 0x2004 :   Mapped variable Type Code of CAN-2000C Module */
                    UNS8 _highestSubIndex_obj2004 = 8; /* number of subindex - 1*/
                    subindex _Index2004[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj2004 },
                       { RW, uint8, sizeof (UNS8), (void*)&Type_Code_of_CAN_2000C_Module_Type_Code_of_PO_ch0 },
                       { RW, uint8, sizeof (UNS8), (void*)&Type_Code_of_CAN_2000C_Module_Type_Code_of_PO_ch1 },
                       { RW, uint8, sizeof (UNS8), (void*)&Type_Code_of_CAN_2000C_Module_Type_Code_of_PO_ch2 },
                       { RW, uint8, sizeof (UNS8), (void*)&Type_Code_of_CAN_2000C_Module_Type_Code_of_PO_ch3 },
                       { RW, uint8, sizeof (UNS8), (void*)&Type_Code_of_CAN_2000C_Module_Type_Code_of_PO_ch4 },
                       { RW, uint8, sizeof (UNS8), (void*)&Type_Code_of_CAN_2000C_Module_Type_Code_of_PO_ch5 },
                       { RW, uint8, sizeof (UNS8), (void*)&Type_Code_of_CAN_2000C_Module_Type_Code_of_PO_ch6 },
                       { RW, uint8, sizeof (UNS8), (void*)&Type_Code_of_CAN_2000C_Module_Type_Code_of_PO_ch7 }
                     };

/* index 0x3000 :   Mapped variable Read High Speed Counter */
                    UNS8 _highestSubIndex_obj3000 = 8; /* number of subindex - 1*/
                    subindex _Index3000[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj3000 },
                       { RO, uint32, sizeof (UNS32), (void*)&Read_High_Speed_Counter_High_Speed_Counter_ch0 },
                       { RO, uint32, sizeof (UNS32), (void*)&Read_High_Speed_Counter_High_Speed_Counter_ch1 },
                       { RO, uint32, sizeof (UNS32), (void*)&Read_High_Speed_Counter_High_Speed_Counter_ch2 },
                       { RO, uint32, sizeof (UNS32), (void*)&Read_High_Speed_Counter_High_Speed_Counter_ch3 },
                       { RO, uint32, sizeof (UNS32), (void*)&Read_High_Speed_Counter_High_Speed_Counter_ch4 },
                       { RO, uint32, sizeof (UNS32), (void*)&Read_High_Speed_Counter_High_Speed_Counter_ch5 },
                       { RO, uint32, sizeof (UNS32), (void*)&Read_High_Speed_Counter_High_Speed_Counter_ch6 },
                       { RO, uint32, sizeof (UNS32), (void*)&Read_High_Speed_Counter_High_Speed_Counter_ch7 }
                     };

/* index 0x3002 :   Mapped variable Clear Counter */
                    UNS8 _highestSubIndex_obj3002 = 8; /* number of subindex - 1*/
                    subindex _Index3002[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj3002 },
                       { WO, uint8, sizeof (UNS8), (void*)&Clear_Counter_Clear_Counter_ch0 },
                       { WO, uint8, sizeof (UNS8), (void*)&Clear_Counter_Clear_Counter_ch1 },
                       { WO, uint8, sizeof (UNS8), (void*)&Clear_Counter_Clear_Counter_ch2 },
                       { WO, uint8, sizeof (UNS8), (void*)&Clear_Counter_Clear_Counter_ch3 },
                       { WO, uint8, sizeof (UNS8), (void*)&Clear_Counter_Clear_Counter_ch4 },
                       { WO, uint8, sizeof (UNS8), (void*)&Clear_Counter_Clear_Counter_ch5 },
                       { WO, uint8, sizeof (UNS8), (void*)&Clear_Counter_Clear_Counter_ch6 },
                       { WO, uint8, sizeof (UNS8), (void*)&Clear_Counter_Clear_Counter_ch7 }
                     };

/* index 0x3100 :   Mapped variable Pulse Output Start */
                    UNS8 _highestSubIndex_obj3100 = 8; /* number of subindex - 1*/
                    subindex _Index3100[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj3100 },
                       { RW, uint8, sizeof (UNS8), (void*)&Pulse_Output_Start_Pulse_Outputs_ch0 },
                       { RW, uint8, sizeof (UNS8), (void*)&Pulse_Output_Start_Pulse_Outputs_ch1 },
                       { RW, uint8, sizeof (UNS8), (void*)&Pulse_Output_Start_Pulse_Outputs_ch2 },
                       { RW, uint8, sizeof (UNS8), (void*)&Pulse_Output_Start_Pulse_Outputs_ch3 },
                       { RW, uint8, sizeof (UNS8), (void*)&Pulse_Output_Start_Pulse_Outputs_ch4 },
                       { RW, uint8, sizeof (UNS8), (void*)&Pulse_Output_Start_Pulse_Outputs_ch5 },
                       { RW, uint8, sizeof (UNS8), (void*)&Pulse_Output_Start_Pulse_Outputs_ch6 },
                       { RW, uint8, sizeof (UNS8), (void*)&Pulse_Output_Start_Pulse_Outputs_ch7 }
                     };

/* index 0x3101 :   Mapped variable Set Burst Count 16-Bit */
                    UNS8 _highestSubIndex_obj3101 = 8; /* number of subindex - 1*/
                    subindex _Index3101[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj3101 },
                       { RW, uint16, sizeof (UNS16), (void*)&Set_Burst_Count_16_Bit_Burst_Count_ch0 },
                       { RW, uint16, sizeof (UNS16), (void*)&Set_Burst_Count_16_Bit_Burst_Count_ch1 },
                       { RW, uint16, sizeof (UNS16), (void*)&Set_Burst_Count_16_Bit_Burst_Count_ch2 },
                       { RW, uint16, sizeof (UNS16), (void*)&Set_Burst_Count_16_Bit_Burst_Count_ch3 },
                       { RW, uint16, sizeof (UNS16), (void*)&Set_Burst_Count_16_Bit_Burst_Count_ch4 },
                       { RW, uint16, sizeof (UNS16), (void*)&Set_Burst_Count_16_Bit_Burst_Count_ch5 },
                       { RW, uint16, sizeof (UNS16), (void*)&Set_Burst_Count_16_Bit_Burst_Count_ch6 },
                       { RW, uint16, sizeof (UNS16), (void*)&Set_Burst_Count_16_Bit_Burst_Count_ch7 }
                     };

/* index 0x3102 :   Mapped variable Set Pulse Frequency 32-Bit */
                    UNS8 _highestSubIndex_obj3102 = 8; /* number of subindex - 1*/
                    subindex _Index3102[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj3102 },
                       { RW, uint32, sizeof (UNS32), (void*)&Set_Pulse_Frequency_32_Bit_Pulse_Frequency_ch0 },
                       { RW, uint32, sizeof (UNS32), (void*)&Set_Pulse_Frequency_32_Bit_Pulse_Frequency_ch1 },
                       { RW, uint32, sizeof (UNS32), (void*)&Set_Pulse_Frequency_32_Bit_Pulse_Frequency_ch2 },
                       { RW, uint32, sizeof (UNS32), (void*)&Set_Pulse_Frequency_32_Bit_Pulse_Frequency_ch3 },
                       { RW, uint32, sizeof (UNS32), (void*)&Set_Pulse_Frequency_32_Bit_Pulse_Frequency_ch4 },
                       { RW, uint32, sizeof (UNS32), (void*)&Set_Pulse_Frequency_32_Bit_Pulse_Frequency_ch5 },
                       { RW, uint32, sizeof (UNS32), (void*)&Set_Pulse_Frequency_32_Bit_Pulse_Frequency_ch6 },
                       { RW, uint32, sizeof (UNS32), (void*)&Set_Pulse_Frequency_32_Bit_Pulse_Frequency_ch7 }
                     };

/* index 0x3103 :   Mapped variable Set Pulse Duty (%) 16-Bit */
                    UNS8 _highestSubIndex_obj3103 = 8; /* number of subindex - 1*/
                    subindex _Index3103[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj3103 },
                       { RW, uint16, sizeof (UNS16), (void*)&Set_Pulse_Duty_16_Bit_Pulse_Duty_ch0 },
                       { RW, uint16, sizeof (UNS16), (void*)&Set_Pulse_Duty_16_Bit_Pulse_Duty_ch1 },
                       { RW, uint16, sizeof (UNS16), (void*)&Set_Pulse_Duty_16_Bit_Pulse_Duty_ch2 },
                       { RW, uint16, sizeof (UNS16), (void*)&Set_Pulse_Duty_16_Bit_Pulse_Duty_ch3 },
                       { RW, uint16, sizeof (UNS16), (void*)&Set_Pulse_Duty_16_Bit_Pulse_Duty_ch4 },
                       { RW, uint16, sizeof (UNS16), (void*)&Set_Pulse_Duty_16_Bit_Pulse_Duty_ch5 },
                       { RW, uint16, sizeof (UNS16), (void*)&Set_Pulse_Duty_16_Bit_Pulse_Duty_ch6 },
                       { RW, uint16, sizeof (UNS16), (void*)&Set_Pulse_Duty_16_Bit_Pulse_Duty_ch7 }
                     };

/* index 0x3104 :   Mapped variable Set Hardware Trig 8-Bit */
                    UNS8 _highestSubIndex_obj3104 = 8; /* number of subindex - 1*/
                    subindex _Index3104[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj3104 },
                       { RW, uint8, sizeof (UNS8), (void*)&Set_Hardware_Trig_8_Bit_Hardware_Trig_ch0 },
                       { RW, uint8, sizeof (UNS8), (void*)&Set_Hardware_Trig_8_Bit_Hardware_Trig_ch1 },
                       { RW, uint8, sizeof (UNS8), (void*)&Set_Hardware_Trig_8_Bit_Hardware_Trig_ch2 },
                       { RW, uint8, sizeof (UNS8), (void*)&Set_Hardware_Trig_8_Bit_Hardware_Trig_ch3 },
                       { RW, uint8, sizeof (UNS8), (void*)&Set_Hardware_Trig_8_Bit_Hardware_Trig_ch4 },
                       { RW, uint8, sizeof (UNS8), (void*)&Set_Hardware_Trig_8_Bit_Hardware_Trig_ch5 },
                       { RW, uint8, sizeof (UNS8), (void*)&Set_Hardware_Trig_8_Bit_Hardware_Trig_ch6 },
                       { RW, uint8, sizeof (UNS8), (void*)&Set_Hardware_Trig_8_Bit_Hardware_Trig_ch7 }
                     };

/* index 0x3105 :   Mapped variable Set Sync Channel 8-Bit */
                    UNS8 _highestSubIndex_obj3105 = 8; /* number of subindex - 1*/
                    subindex _Index3105[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj3105 },
                       { RW, uint8, sizeof (UNS8), (void*)&Set_Sync_Channel_8_Bit_Sync_Channel_ch0 },
                       { RW, uint8, sizeof (UNS8), (void*)&Set_Sync_Channel_8_Bit_Sync_Channel_ch1 },
                       { RW, uint8, sizeof (UNS8), (void*)&Set_Sync_Channel_8_Bit_Sync_Channel_ch2 },
                       { RW, uint8, sizeof (UNS8), (void*)&Set_Sync_Channel_8_Bit_Sync_Channel_ch3 },
                       { RW, uint8, sizeof (UNS8), (void*)&Set_Sync_Channel_8_Bit_Sync_Channel_ch4 },
                       { RW, uint8, sizeof (UNS8), (void*)&Set_Sync_Channel_8_Bit_Sync_Channel_ch5 },
                       { RW, uint8, sizeof (UNS8), (void*)&Set_Sync_Channel_8_Bit_Sync_Channel_ch6 },
                       { RW, uint8, sizeof (UNS8), (void*)&Set_Sync_Channel_8_Bit_Sync_Channel_ch7 }
                     };

/* index 0x3106 :   Mapped variable Set Sync Start 8-Bit */
                    UNS8 _highestSubIndex_obj3106 = 1; /* number of subindex - 1*/
                    subindex _Index3106[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj3106 },
                       { RW, uint8, sizeof (UNS8), (void*)&Set_Sync_Start_8_Bit_Sync_Start }
                     };

/* index 0x3110 :   Mapped variable Set Deceleration 16-Bit */
                    UNS8 _highestSubIndex_obj3110 = 8; /* number of subindex - 1*/
                    subindex _Index3110[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj3110 },
                       { RW, uint16, sizeof (UNS16), (void*)&Set_Deceleration_16_Bit_Deceleration_ch0 },
                       { RW, uint16, sizeof (UNS16), (void*)&Set_Deceleration_16_Bit_Deceleration_ch1 },
                       { RW, uint16, sizeof (UNS16), (void*)&Set_Deceleration_16_Bit_Deceleration_ch2 },
                       { RW, uint16, sizeof (UNS16), (void*)&Set_Deceleration_16_Bit_Deceleration_ch3 },
                       { RW, uint16, sizeof (UNS16), (void*)&Set_Deceleration_16_Bit_Deceleration_ch4 },
                       { RW, uint16, sizeof (UNS16), (void*)&Set_Deceleration_16_Bit_Deceleration_ch5 },
                       { RW, uint16, sizeof (UNS16), (void*)&Set_Deceleration_16_Bit_Deceleration_ch6 },
                       { RW, uint16, sizeof (UNS16), (void*)&Set_Deceleration_16_Bit_Deceleration_ch7 }
                     };

/* index 0x3111 :   Mapped variable Set Acceleration 16-Bit */
                    UNS8 _highestSubIndex_obj3111 = 8; /* number of subindex - 1*/
                    subindex _Index3111[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj3111 },
                       { RW, uint16, sizeof (UNS16), (void*)&Set_Acceleration_16_Bit_Acceleration_ch0 },
                       { RW, uint16, sizeof (UNS16), (void*)&Set_Acceleration_16_Bit_Acceleration_ch1 },
                       { RW, uint16, sizeof (UNS16), (void*)&Set_Acceleration_16_Bit_Acceleration_ch2 },
                       { RW, uint16, sizeof (UNS16), (void*)&Set_Acceleration_16_Bit_Acceleration_ch3 },
                       { RW, uint16, sizeof (UNS16), (void*)&Set_Acceleration_16_Bit_Acceleration_ch4 },
                       { RW, uint16, sizeof (UNS16), (void*)&Set_Acceleration_16_Bit_Acceleration_ch5 },
                       { RW, uint16, sizeof (UNS16), (void*)&Set_Acceleration_16_Bit_Acceleration_ch6 },
                       { RW, uint16, sizeof (UNS16), (void*)&Set_Acceleration_16_Bit_Acceleration_ch7 }
                     };

/* index 0x3112 :   Mapped variable Set Channel Group 8-Bit */
                    UNS8 _highestSubIndex_obj3112 = 8; /* number of subindex - 1*/
                    subindex _Index3112[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj3112 },
                       { RW, uint8, sizeof (UNS8), (void*)&Set_Channel_Group_8_Bit_Channel_Group_ch0 },
                       { RW, uint8, sizeof (UNS8), (void*)&Set_Channel_Group_8_Bit_Channel_Group_ch1 },
                       { RW, uint8, sizeof (UNS8), (void*)&Set_Channel_Group_8_Bit_Channel_Group_ch2 },
                       { RW, uint8, sizeof (UNS8), (void*)&Set_Channel_Group_8_Bit_Channel_Group_ch3 },
                       { RW, uint8, sizeof (UNS8), (void*)&Set_Channel_Group_8_Bit_Channel_Group_ch4 },
                       { RW, uint8, sizeof (UNS8), (void*)&Set_Channel_Group_8_Bit_Channel_Group_ch5 },
                       { RW, uint8, sizeof (UNS8), (void*)&Set_Channel_Group_8_Bit_Channel_Group_ch6 },
                       { RW, uint8, sizeof (UNS8), (void*)&Set_Channel_Group_8_Bit_Channel_Group_ch7 }
                     };

/* index 0x6000 :   Mapped variable Read Inputs 8 Bit */
                    UNS8 _highestSubIndex_obj6000 = 1; /* number of subindex - 1*/
                    subindex _Index6000[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj6000 },
                       { RO, uint8, sizeof (UNS8), (void*)&Read_Inputs_8_Bit[0] }
                     };

/**************************************************************************/
/* Declaration of pointed variables                                       */
/**************************************************************************/

const indextable _objdict[] = 
{
  { (subindex*)_Index1000,sizeof(_Index1000)/sizeof(_Index1000[0]), 0x1000},
  { (subindex*)_Index1001,sizeof(_Index1001)/sizeof(_Index1001[0]), 0x1001},
  { (subindex*)_Index1003,sizeof(_Index1003)/sizeof(_Index1003[0]), 0x1003},
  { (subindex*)_Index1005,sizeof(_Index1005)/sizeof(_Index1005[0]), 0x1005},
  { (subindex*)_Index1008,sizeof(_Index1008)/sizeof(_Index1008[0]), 0x1008},
  { (subindex*)_Index1009,sizeof(_Index1009)/sizeof(_Index1009[0]), 0x1009},
  { (subindex*)_Index100A,sizeof(_Index100A)/sizeof(_Index100A[0]), 0x100A},
  { (subindex*)_Index100C,sizeof(_Index100C)/sizeof(_Index100C[0]), 0x100C},
  { (subindex*)_Index100D,sizeof(_Index100D)/sizeof(_Index100D[0]), 0x100D},
  { (subindex*)_Index1010,sizeof(_Index1010)/sizeof(_Index1010[0]), 0x1010},
  { (subindex*)_Index1011,sizeof(_Index1011)/sizeof(_Index1011[0]), 0x1011},
  { (subindex*)_Index1014,sizeof(_Index1014)/sizeof(_Index1014[0]), 0x1014},
  { (subindex*)_Index1017,sizeof(_Index1017)/sizeof(_Index1017[0]), 0x1017},
  { (subindex*)_Index1018,sizeof(_Index1018)/sizeof(_Index1018[0]), 0x1018},
  { (subindex*)_Index1200,sizeof(_Index1200)/sizeof(_Index1200[0]), 0x1200},
  { (subindex*)_Index1400,sizeof(_Index1400)/sizeof(_Index1400[0]), 0x1400},
  { (subindex*)_Index1401,sizeof(_Index1401)/sizeof(_Index1401[0]), 0x1401},
  { (subindex*)_Index1402,sizeof(_Index1402)/sizeof(_Index1402[0]), 0x1402},
  { (subindex*)_Index1403,sizeof(_Index1403)/sizeof(_Index1403[0]), 0x1403},
  { (subindex*)_Index1404,sizeof(_Index1404)/sizeof(_Index1404[0]), 0x1404},
  { (subindex*)_Index1405,sizeof(_Index1405)/sizeof(_Index1405[0]), 0x1405},
  { (subindex*)_Index1406,sizeof(_Index1406)/sizeof(_Index1406[0]), 0x1406},
  { (subindex*)_Index1407,sizeof(_Index1407)/sizeof(_Index1407[0]), 0x1407},
  { (subindex*)_Index1408,sizeof(_Index1408)/sizeof(_Index1408[0]), 0x1408},
  { (subindex*)_Index1409,sizeof(_Index1409)/sizeof(_Index1409[0]), 0x1409},
  { (subindex*)_Index1600,sizeof(_Index1600)/sizeof(_Index1600[0]), 0x1600},
  { (subindex*)_Index1601,sizeof(_Index1601)/sizeof(_Index1601[0]), 0x1601},
  { (subindex*)_Index1602,sizeof(_Index1602)/sizeof(_Index1602[0]), 0x1602},
  { (subindex*)_Index1603,sizeof(_Index1603)/sizeof(_Index1603[0]), 0x1603},
  { (subindex*)_Index1604,sizeof(_Index1604)/sizeof(_Index1604[0]), 0x1604},
  { (subindex*)_Index1605,sizeof(_Index1605)/sizeof(_Index1605[0]), 0x1605},
  { (subindex*)_Index1606,sizeof(_Index1606)/sizeof(_Index1606[0]), 0x1606},
  { (subindex*)_Index1607,sizeof(_Index1607)/sizeof(_Index1607[0]), 0x1607},
  { (subindex*)_Index1608,sizeof(_Index1608)/sizeof(_Index1608[0]), 0x1608},
  { (subindex*)_Index1609,sizeof(_Index1609)/sizeof(_Index1609[0]), 0x1609},
  { (subindex*)_Index1800,sizeof(_Index1800)/sizeof(_Index1800[0]), 0x1800},
  { (subindex*)_Index1801,sizeof(_Index1801)/sizeof(_Index1801[0]), 0x1801},
  { (subindex*)_Index1802,sizeof(_Index1802)/sizeof(_Index1802[0]), 0x1802},
  { (subindex*)_Index1803,sizeof(_Index1803)/sizeof(_Index1803[0]), 0x1803},
  { (subindex*)_Index1804,sizeof(_Index1804)/sizeof(_Index1804[0]), 0x1804},
  { (subindex*)_Index1805,sizeof(_Index1805)/sizeof(_Index1805[0]), 0x1805},
  { (subindex*)_Index1806,sizeof(_Index1806)/sizeof(_Index1806[0]), 0x1806},
  { (subindex*)_Index1807,sizeof(_Index1807)/sizeof(_Index1807[0]), 0x1807},
  { (subindex*)_Index1808,sizeof(_Index1808)/sizeof(_Index1808[0]), 0x1808},
  { (subindex*)_Index1809,sizeof(_Index1809)/sizeof(_Index1809[0]), 0x1809},
  { (subindex*)_Index1A00,sizeof(_Index1A00)/sizeof(_Index1A00[0]), 0x1A00},
  { (subindex*)_Index1A01,sizeof(_Index1A01)/sizeof(_Index1A01[0]), 0x1A01},
  { (subindex*)_Index1A02,sizeof(_Index1A02)/sizeof(_Index1A02[0]), 0x1A02},
  { (subindex*)_Index1A03,sizeof(_Index1A03)/sizeof(_Index1A03[0]), 0x1A03},
  { (subindex*)_Index1A04,sizeof(_Index1A04)/sizeof(_Index1A04[0]), 0x1A04},
  { (subindex*)_Index1A05,sizeof(_Index1A05)/sizeof(_Index1A05[0]), 0x1A05},
  { (subindex*)_Index1A06,sizeof(_Index1A06)/sizeof(_Index1A06[0]), 0x1A06},
  { (subindex*)_Index1A07,sizeof(_Index1A07)/sizeof(_Index1A07[0]), 0x1A07},
  { (subindex*)_Index1A08,sizeof(_Index1A08)/sizeof(_Index1A08[0]), 0x1A08},
  { (subindex*)_Index1A09,sizeof(_Index1A09)/sizeof(_Index1A09[0]), 0x1A09},
  { (subindex*)_Index2004,sizeof(_Index2004)/sizeof(_Index2004[0]), 0x2004},
  { (subindex*)_Index3000,sizeof(_Index3000)/sizeof(_Index3000[0]), 0x3000},
  { (subindex*)_Index3002,sizeof(_Index3002)/sizeof(_Index3002[0]), 0x3002},
  { (subindex*)_Index3100,sizeof(_Index3100)/sizeof(_Index3100[0]), 0x3100},
  { (subindex*)_Index3101,sizeof(_Index3101)/sizeof(_Index3101[0]), 0x3101},
  { (subindex*)_Index3102,sizeof(_Index3102)/sizeof(_Index3102[0]), 0x3102},
  { (subindex*)_Index3103,sizeof(_Index3103)/sizeof(_Index3103[0]), 0x3103},
  { (subindex*)_Index3104,sizeof(_Index3104)/sizeof(_Index3104[0]), 0x3104},
  { (subindex*)_Index3105,sizeof(_Index3105)/sizeof(_Index3105[0]), 0x3105},
  { (subindex*)_Index3106,sizeof(_Index3106)/sizeof(_Index3106[0]), 0x3106},
  { (subindex*)_Index3110,sizeof(_Index3110)/sizeof(_Index3110[0]), 0x3110},
  { (subindex*)_Index3111,sizeof(_Index3111)/sizeof(_Index3111[0]), 0x3111},
  { (subindex*)_Index3112,sizeof(_Index3112)/sizeof(_Index3112[0]), 0x3112},
  { (subindex*)_Index6000,sizeof(_Index6000)/sizeof(_Index6000[0]), 0x6000},
};

const indextable * _scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks)
{
	int i;
	*callbacks = NULL;
	switch(wIndex){
		case 0x1000: i = 0;break;
		case 0x1001: i = 1;break;
		case 0x1003: i = 2;*callbacks = _Index1003_callbacks; break;
		case 0x1005: i = 3;*callbacks = _Index1005_callbacks; break;
		case 0x1008: i = 4;break;
		case 0x1009: i = 5;break;
		case 0x100A: i = 6;break;
		case 0x100C: i = 7;break;
		case 0x100D: i = 8;break;
		case 0x1010: i = 9;break;
		case 0x1011: i = 10;break;
		case 0x1014: i = 11;break;
		case 0x1017: i = 12;*callbacks = _Index1017_callbacks; break;
		case 0x1018: i = 13;break;
		case 0x1200: i = 14;break;
		case 0x1400: i = 15;break;
		case 0x1401: i = 16;break;
		case 0x1402: i = 17;break;
		case 0x1403: i = 18;break;
		case 0x1404: i = 19;break;
		case 0x1405: i = 20;break;
		case 0x1406: i = 21;break;
		case 0x1407: i = 22;break;
		case 0x1408: i = 23;break;
		case 0x1409: i = 24;break;
		case 0x1600: i = 25;break;
		case 0x1601: i = 26;break;
		case 0x1602: i = 27;break;
		case 0x1603: i = 28;break;
		case 0x1604: i = 29;break;
		case 0x1605: i = 30;break;
		case 0x1606: i = 31;break;
		case 0x1607: i = 32;break;
		case 0x1608: i = 33;break;
		case 0x1609: i = 34;break;
		case 0x1800: i = 35;*callbacks = _Index1800_callbacks; break;
		case 0x1801: i = 36;*callbacks = _Index1801_callbacks; break;
		case 0x1802: i = 37;*callbacks = _Index1802_callbacks; break;
		case 0x1803: i = 38;*callbacks = _Index1803_callbacks; break;
		case 0x1804: i = 39;*callbacks = _Index1804_callbacks; break;
		case 0x1805: i = 40;*callbacks = _Index1805_callbacks; break;
		case 0x1806: i = 41;*callbacks = _Index1806_callbacks; break;
		case 0x1807: i = 42;*callbacks = _Index1807_callbacks; break;
		case 0x1808: i = 43;*callbacks = _Index1808_callbacks; break;
		case 0x1809: i = 44;*callbacks = _Index1809_callbacks; break;
		case 0x1A00: i = 45;break;
		case 0x1A01: i = 46;break;
		case 0x1A02: i = 47;break;
		case 0x1A03: i = 48;break;
		case 0x1A04: i = 49;break;
		case 0x1A05: i = 50;break;
		case 0x1A06: i = 51;break;
		case 0x1A07: i = 52;break;
		case 0x1A08: i = 53;break;
		case 0x1A09: i = 54;break;
		case 0x2004: i = 55;break;
		case 0x3000: i = 56;break;
		case 0x3002: i = 57;break;
		case 0x3100: i = 58;break;
		case 0x3101: i = 59;break;
		case 0x3102: i = 60;break;
		case 0x3103: i = 61;break;
		case 0x3104: i = 62;break;
		case 0x3105: i = 63;break;
		case 0x3106: i = 64;break;
		case 0x3110: i = 65;break;
		case 0x3111: i = 66;break;
		case 0x3112: i = 67;break;
		case 0x6000: i = 68;break;
		default:
			*errorCode = OD_NO_SUCH_OBJECT;
			return NULL;
	}
	*errorCode = OD_SUCCESSFUL;
	return &_objdict[i];
}

/* 
 * To count at which received SYNC a PDO must be sent.
 * Even if no pdoTransmit are defined, at least one entry is computed
 * for compilations issues.
 */
s_PDO_status _PDO_status[10] = {s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer};

const quick_index _firstIndex = {
  14, /* SDO_SVR */
  0, /* SDO_CLT */
  15, /* PDO_RCV */
  25, /* PDO_RCV_MAP */
  35, /* PDO_TRS */
  45 /* PDO_TRS_MAP */
};

const quick_index _lastIndex = {
  14, /* SDO_SVR */
  0, /* SDO_CLT */
  24, /* PDO_RCV */
  34, /* PDO_RCV_MAP */
  44, /* PDO_TRS */
  54 /* PDO_TRS_MAP */
};

const UNS16 _ObjdictSize = sizeof(_objdict)/sizeof(_objdict[0]); 

CO_Data _Data = CANOPEN_NODE_DATA_INITIALIZER();

