
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef CAN_2057_H
#define CAN_2057_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 _valueRangeTest (UNS8 typeValue, void * value);
const indextable * _scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks);

/* Master node data struct */
extern CO_Data _Data;
extern UNS8 Power_On_Value_of_CAN_2000C_Module_Power_On_Value_of_1h_to_8h;		/* Mapped at index 0x2010, subindex 0x01 */
extern UNS8 Power_On_Value_of_CAN_2000C_Module_Power_On_Value_of_9h_to_15h;		/* Mapped at index 0x2010, subindex 0x02 */
extern UNS8 Write_Outputs_8_Bit[2];		/* Mapped at index 0x6200, subindex 0x01 - 0x02 */
extern UNS8 Change_Polarity_Outputs_8_Bit[2];		/* Mapped at index 0x6202, subindex 0x01 - 0x02 */
extern UNS8 Error_Mode_Outputs_8_Bit[2];		/* Mapped at index 0x6206, subindex 0x01 - 0x02 */
extern UNS8 Error_Value_Outputs_8_Bit[2];		/* Mapped at index 0x6207, subindex 0x01 - 0x02 */

#endif // CAN_2057_H
