
/* File generated by gen_cfile.py. Should not be modified. */

#include "CAN_2057.h"

/**************************************************************************/
/* Declaration of mapped variables                                        */
/**************************************************************************/
UNS8 Power_On_Value_of_CAN_2000C_Module_Power_On_Value_of_1h_to_8h = 0x0;		/* Mapped at index 0x2010, subindex 0x01 */
UNS8 Power_On_Value_of_CAN_2000C_Module_Power_On_Value_of_9h_to_15h = 0x0;		/* Mapped at index 0x2010, subindex 0x02 */
UNS8 Write_Outputs_8_Bit[] =		/* Mapped at index 0x6200, subindex 0x01 - 0x02 */
  {
    0x0,	/* 0 */
    0x0	/* 0 */
  };
UNS8 Change_Polarity_Outputs_8_Bit[] =		/* Mapped at index 0x6202, subindex 0x01 - 0x02 */
  {
    0x0,	/* 0 */
    0x0	/* 0 */
  };
UNS8 Error_Mode_Outputs_8_Bit[] =		/* Mapped at index 0x6206, subindex 0x01 - 0x02 */
  {
    0xFF,	/* 255 */
    0xFF	/* 255 */
  };
UNS8 Error_Value_Outputs_8_Bit[] =		/* Mapped at index 0x6207, subindex 0x01 - 0x02 */
  {
    0x0,	/* 0 */
    0x0	/* 0 */
  };

/**************************************************************************/
/* Declaration of value range types                                       */
/**************************************************************************/

#define valueRange_EMC 0x9F /* Type for index 0x1003 subindex 0x00 (only set of value 0 is possible) */
UNS32 CAN_2057_valueRangeTest (UNS8 typeValue, void * value)
{
  switch (typeValue) {
    case valueRange_EMC:
      if (*(UNS8*)value != (UNS8)0) return OD_VALUE_RANGE_EXCEEDED;
      break;
  }
  return 0;
}

/**************************************************************************/
/* The node id                                                            */
/**************************************************************************/
/* node_id default value.*/
UNS8 CAN_2057_bDeviceNodeId = 0x00;

/**************************************************************************/
/* Array of message processing information */

const UNS8 CAN_2057_iam_a_slave = 1;

TIMER_HANDLE CAN_2057_heartBeatTimers[1];

/*
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

                               OBJECT DICTIONARY

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
*/

/* index 0x1000 :   Device Type. */
                    UNS32 CAN_2057_obj1000 = 0x20191;	/* 131473 */
                    subindex CAN_2057_Index1000[] =
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&CAN_2057_obj1000 }
                     };

/* index 0x1001 :   Error Register. */
                    UNS8 CAN_2057_obj1001 = 0x0;	/* 0 */
                    subindex CAN_2057_Index1001[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CAN_2057_obj1001 }
                     };

/* index 0x1003 :   Pre-defined Error Field. */
                    UNS8 CAN_2057_highestSubIndex_obj1003 = 0; /* number of subindex - 1*/
                    UNS32 CAN_2057_obj1003[] =
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    ODCallback_t CAN_2057_Index1003_callbacks[] =
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex CAN_2057_Index1003[] =
                     {
                       { RW, valueRange_EMC, sizeof (UNS8), (void*)&CAN_2057_highestSubIndex_obj1003 },
                       { RO, uint32, sizeof (UNS32), (void*)&CAN_2057_obj1003[0] },
                       { RO, uint32, sizeof (UNS32), (void*)&CAN_2057_obj1003[1] },
                       { RO, uint32, sizeof (UNS32), (void*)&CAN_2057_obj1003[2] },
                       { RO, uint32, sizeof (UNS32), (void*)&CAN_2057_obj1003[3] },
                       { RO, uint32, sizeof (UNS32), (void*)&CAN_2057_obj1003[4] }
                     };

/* index 0x1005 :   SYNC COB ID. */
                    UNS32 CAN_2057_obj1005 = 0x80;	/* 128 */
                    ODCallback_t CAN_2057_Index1005_callbacks[] =
                     {
                       NULL,
                     };
                    subindex CAN_2057_Index1005[] =
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&CAN_2057_obj1005 }
                     };

/* index 0x1006 :   Communication / Cycle Period */
                    UNS32 CAN_2057_obj1006 = 0x0;   /* 0 */

/* index 0x1008 :   Manufacturer Device Name. */
                    UNS8 CAN_2057_obj1008[10] = "CAN-2057";
                    subindex CAN_2057_Index1008[] =
                     {
                       { RO, visible_string, 10, (void*)&CAN_2057_obj1008 }
                     };

/* index 0x1009 :   Manufacturer Hardware Version. */
                    UNS8 CAN_2057_obj1009[10] = "1.1";
                    subindex CAN_2057_Index1009[] =
                     {
                       { RO, visible_string, 10, (void*)&CAN_2057_obj1009 }
                     };

/* index 0x100A :   Manufacturer Software Version. */
                    UNS8 CAN_2057_obj100A[13] = "1.00-20100520";
                    subindex CAN_2057_Index100A[] =
                     {
                       { RO, visible_string, 13, (void*)&CAN_2057_obj100A }
                     };

/* index 0x100C :   Guard Time. */
                    UNS16 CAN_2057_obj100C = 0x0;	/* 0 */
                    subindex CAN_2057_Index100C[] =
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&CAN_2057_obj100C }
                     };

/* index 0x100D :   Life Time Factor. */
                    UNS8 CAN_2057_obj100D = 0x0;	/* 0 */
                    subindex CAN_2057_Index100D[] =
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&CAN_2057_obj100D }
                     };

/* index 0x1010 :   Store parameters. */
                    UNS8 CAN_2057_highestSubIndex_obj1010 = 3; /* number of subindex - 1*/
                    UNS32 CAN_2057_obj1010_Save_All_Parameters = 0x0;	/* 0 */
                    UNS32 CAN_2057_obj1010_Save_Communication_Parameters = 0x0;	/* 0 */
                    UNS32 CAN_2057_obj1010_Save_Application_Parameters = 0x0;	/* 0 */
                    subindex CAN_2057_Index1010[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CAN_2057_highestSubIndex_obj1010 },
                       { RW, uint32, sizeof (UNS32), (void*)&CAN_2057_obj1010_Save_All_Parameters },
                       { RW, uint32, sizeof (UNS32), (void*)&CAN_2057_obj1010_Save_Communication_Parameters },
                       { RW, uint32, sizeof (UNS32), (void*)&CAN_2057_obj1010_Save_Application_Parameters }
                     };

/* index 0x1011 :   Restore Default Parameters. */
                    UNS8 CAN_2057_highestSubIndex_obj1011 = 3; /* number of subindex - 1*/
                    UNS32 CAN_2057_obj1011_Restore_All_Default_Parameters = 0x0;	/* 0 */
                    UNS32 CAN_2057_obj1011_Restore_Communication_Default_Parameters = 0x0;	/* 0 */
                    UNS32 CAN_2057_obj1011_Restore_Application_Default_Parameters = 0x0;	/* 0 */
                    subindex CAN_2057_Index1011[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CAN_2057_highestSubIndex_obj1011 },
                       { RW, uint32, sizeof (UNS32), (void*)&CAN_2057_obj1011_Restore_All_Default_Parameters },
                       { RW, uint32, sizeof (UNS32), (void*)&CAN_2057_obj1011_Restore_Communication_Default_Parameters },
                       { RW, uint32, sizeof (UNS32), (void*)&CAN_2057_obj1011_Restore_Application_Default_Parameters }
                     };

/* index 0x1014 :   Emergency COB ID. */
                    UNS32 CAN_2057_obj1014 = 0x80;	/* 128 */
                    subindex CAN_2057_Index1014[] =
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&CAN_2057_obj1014 }
                     };

/* index 0x1016 :   Consumer Heartbeat Time */
                    UNS8 CAN_2057_highestSubIndex_obj1016 = 0;
                    UNS32 CAN_2057_obj1016[]={0};

/* index 0x1017 :   Producer Heartbeat Time. */
                    UNS16 CAN_2057_obj1017 = 0x0;	/* 0 */
                    ODCallback_t CAN_2057_Index1017_callbacks[] =
                     {
                       NULL,
                     };
                    subindex CAN_2057_Index1017[] =
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&CAN_2057_obj1017 }
                     };

/* index 0x1018 :   Identity. */
                    UNS8 CAN_2057_highestSubIndex_obj1018 = 4; /* number of subindex - 1*/
                    UNS32 CAN_2057_obj1018_Vendor_ID = 0x13C;	/* 316 */
                    UNS32 CAN_2057_obj1018_Product_Code = 0x2057;	/* 8279 */
                    UNS32 CAN_2057_obj1018_Revision_Number = 0x40004;	/* 262148 */
                    UNS32 CAN_2057_obj1018_Serial_Number = 0x6CD3683C;	/* 1825794108 */
                    subindex CAN_2057_Index1018[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CAN_2057_highestSubIndex_obj1018 },
                       { RO, uint32, sizeof (UNS32), (void*)&CAN_2057_obj1018_Vendor_ID },
                       { RO, uint32, sizeof (UNS32), (void*)&CAN_2057_obj1018_Product_Code },
                       { RO, uint32, sizeof (UNS32), (void*)&CAN_2057_obj1018_Revision_Number },
                       { RO, uint32, sizeof (UNS32), (void*)&CAN_2057_obj1018_Serial_Number }
                     };

/* index 0x1200 :   Server SDO Parameter. */
                    UNS8 CAN_2057_highestSubIndex_obj1200 = 2; /* number of subindex - 1*/
                    UNS32 CAN_2057_obj1200_COB_ID_Client_to_Server_Receive_SDO = 0x600;	/* 1536 */
                    UNS32 CAN_2057_obj1200_COB_ID_Server_to_Client_Transmit_SDO = 0x580;	/* 1408 */
                    subindex CAN_2057_Index1200[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CAN_2057_highestSubIndex_obj1200 },
                       { RO, uint32, sizeof (UNS32), (void*)&CAN_2057_obj1200_COB_ID_Client_to_Server_Receive_SDO },
                       { RO, uint32, sizeof (UNS32), (void*)&CAN_2057_obj1200_COB_ID_Server_to_Client_Transmit_SDO }
                     };

/* index 0x1400 :   Receive PDO 1 Parameter. */
                    UNS8 CAN_2057_highestSubIndex_obj1400 = 2; /* number of subindex - 1*/
                    UNS32 CAN_2057_obj1400_COB_ID_used_by_PDO = 0x200;	/* 512 */
                    UNS8 CAN_2057_obj1400_Transmission_Type = 0xFF;	/* 255 */
                    subindex CAN_2057_Index1400[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CAN_2057_highestSubIndex_obj1400 },
                       { RW, uint32, sizeof (UNS32), (void*)&CAN_2057_obj1400_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&CAN_2057_obj1400_Transmission_Type }
                     };

/* index 0x1401 :   Receive PDO 2 Parameter. */
                    UNS8 CAN_2057_highestSubIndex_obj1401 = 2; /* number of subindex - 1*/
                    UNS32 CAN_2057_obj1401_COB_ID_used_by_PDO = 0x300;	/* 768 */
                    UNS8 CAN_2057_obj1401_Transmission_Type = 0xFF;	/* 255 */
                    subindex CAN_2057_Index1401[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CAN_2057_highestSubIndex_obj1401 },
                       { RW, uint32, sizeof (UNS32), (void*)&CAN_2057_obj1401_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&CAN_2057_obj1401_Transmission_Type }
                     };

/* index 0x1402 :   Receive PDO 3 Parameter. */
                    UNS8 CAN_2057_highestSubIndex_obj1402 = 2; /* number of subindex - 1*/
                    UNS32 CAN_2057_obj1402_COB_ID_used_by_PDO = 0x400;	/* 1024 */
                    UNS8 CAN_2057_obj1402_Transmission_Type = 0xFF;	/* 255 */
                    subindex CAN_2057_Index1402[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CAN_2057_highestSubIndex_obj1402 },
                       { RW, uint32, sizeof (UNS32), (void*)&CAN_2057_obj1402_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&CAN_2057_obj1402_Transmission_Type }
                     };

/* index 0x1403 :   Receive PDO 4 Parameter. */
                    UNS8 CAN_2057_highestSubIndex_obj1403 = 2; /* number of subindex - 1*/
                    UNS32 CAN_2057_obj1403_COB_ID_used_by_PDO = 0x500;	/* 1280 */
                    UNS8 CAN_2057_obj1403_Transmission_Type = 0xFF;	/* 255 */
                    subindex CAN_2057_Index1403[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CAN_2057_highestSubIndex_obj1403 },
                       { RW, uint32, sizeof (UNS32), (void*)&CAN_2057_obj1403_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&CAN_2057_obj1403_Transmission_Type }
                     };

/* index 0x1404 :   Receive PDO 5 Parameter. */
                    UNS8 CAN_2057_highestSubIndex_obj1404 = 2; /* number of subindex - 1*/
                    UNS32 CAN_2057_obj1404_COB_ID_used_by_PDO = 0xC0000000;	/* 3221225472 */
                    UNS8 CAN_2057_obj1404_Transmission_Type = 0xFF;	/* 255 */
                    subindex CAN_2057_Index1404[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CAN_2057_highestSubIndex_obj1404 },
                       { RW, uint32, sizeof (UNS32), (void*)&CAN_2057_obj1404_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&CAN_2057_obj1404_Transmission_Type }
                     };

/* index 0x1405 :   Receive PDO 6 Parameter. */
                    UNS8 CAN_2057_highestSubIndex_obj1405 = 2; /* number of subindex - 1*/
                    UNS32 CAN_2057_obj1405_COB_ID_used_by_PDO = 0xC0000000;	/* 3221225472 */
                    UNS8 CAN_2057_obj1405_Transmission_Type = 0xFF;	/* 255 */
                    subindex CAN_2057_Index1405[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CAN_2057_highestSubIndex_obj1405 },
                       { RW, uint32, sizeof (UNS32), (void*)&CAN_2057_obj1405_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&CAN_2057_obj1405_Transmission_Type }
                     };

/* index 0x1406 :   Receive PDO 7 Parameter. */
                    UNS8 CAN_2057_highestSubIndex_obj1406 = 2; /* number of subindex - 1*/
                    UNS32 CAN_2057_obj1406_COB_ID_used_by_PDO = 0xC0000000;	/* 3221225472 */
                    UNS8 CAN_2057_obj1406_Transmission_Type = 0xFF;	/* 255 */
                    subindex CAN_2057_Index1406[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CAN_2057_highestSubIndex_obj1406 },
                       { RW, uint32, sizeof (UNS32), (void*)&CAN_2057_obj1406_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&CAN_2057_obj1406_Transmission_Type }
                     };

/* index 0x1407 :   Receive PDO 8 Parameter. */
                    UNS8 CAN_2057_highestSubIndex_obj1407 = 2; /* number of subindex - 1*/
                    UNS32 CAN_2057_obj1407_COB_ID_used_by_PDO = 0xC0000000;	/* 3221225472 */
                    UNS8 CAN_2057_obj1407_Transmission_Type = 0xFF;	/* 255 */
                    subindex CAN_2057_Index1407[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CAN_2057_highestSubIndex_obj1407 },
                       { RW, uint32, sizeof (UNS32), (void*)&CAN_2057_obj1407_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&CAN_2057_obj1407_Transmission_Type }
                     };

/* index 0x1408 :   Receive PDO 9 Parameter. */
                    UNS8 CAN_2057_highestSubIndex_obj1408 = 2; /* number of subindex - 1*/
                    UNS32 CAN_2057_obj1408_COB_ID_used_by_PDO = 0xC0000000;	/* 3221225472 */
                    UNS8 CAN_2057_obj1408_Transmission_Type = 0xFF;	/* 255 */
                    subindex CAN_2057_Index1408[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CAN_2057_highestSubIndex_obj1408 },
                       { RW, uint32, sizeof (UNS32), (void*)&CAN_2057_obj1408_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&CAN_2057_obj1408_Transmission_Type }
                     };

/* index 0x1409 :   Receive PDO 10 Parameter. */
                    UNS8 CAN_2057_highestSubIndex_obj1409 = 2; /* number of subindex - 1*/
                    UNS32 CAN_2057_obj1409_COB_ID_used_by_PDO = 0xC0000000;	/* 3221225472 */
                    UNS8 CAN_2057_obj1409_Transmission_Type = 0xFF;	/* 255 */
                    subindex CAN_2057_Index1409[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CAN_2057_highestSubIndex_obj1409 },
                       { RW, uint32, sizeof (UNS32), (void*)&CAN_2057_obj1409_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&CAN_2057_obj1409_Transmission_Type }
                     };

/* index 0x1600 :   Receive PDO 1 Mapping. */
                    UNS8 CAN_2057_highestSubIndex_obj1600 = 2; /* number of subindex - 1*/
                    UNS32 CAN_2057_obj1600[] =
                    {
                      0x62000108,	/* 1644167432 */
                      0x62000208	/* 1644167688 */
                    };
                    subindex CAN_2057_Index1600[] =
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&CAN_2057_highestSubIndex_obj1600 },
                       { RW, uint32, sizeof (UNS32), (void*)&CAN_2057_obj1600[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&CAN_2057_obj1600[1] }
                     };

/* index 0x1601 :   Receive PDO 2 Mapping. */
                    UNS8 CAN_2057_highestSubIndex_obj1601 = 0; /* number of subindex - 1*/
                    UNS32 CAN_2057_obj1601[] =
                    {
                    };
                    subindex CAN_2057_Index1601[] =
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&CAN_2057_highestSubIndex_obj1601 }
                     };

/* index 0x1602 :   Receive PDO 3 Mapping. */
                    UNS8 CAN_2057_highestSubIndex_obj1602 = 0; /* number of subindex - 1*/
                    UNS32 CAN_2057_obj1602[] =
                    {
                    };
                    subindex CAN_2057_Index1602[] =
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&CAN_2057_highestSubIndex_obj1602 }
                     };

/* index 0x1603 :   Receive PDO 4 Mapping. */
                    UNS8 CAN_2057_highestSubIndex_obj1603 = 0; /* number of subindex - 1*/
                    UNS32 CAN_2057_obj1603[] =
                    {
                    };
                    subindex CAN_2057_Index1603[] =
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&CAN_2057_highestSubIndex_obj1603 }
                     };

/* index 0x1604 :   Receive PDO 5 Mapping. */
                    UNS8 CAN_2057_highestSubIndex_obj1604 = 0; /* number of subindex - 1*/
                    UNS32 CAN_2057_obj1604[] =
                    {
                    };
                    subindex CAN_2057_Index1604[] =
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&CAN_2057_highestSubIndex_obj1604 }
                     };

/* index 0x1605 :   Receive PDO 6 Mapping. */
                    UNS8 CAN_2057_highestSubIndex_obj1605 = 0; /* number of subindex - 1*/
                    UNS32 CAN_2057_obj1605[] =
                    {
                    };
                    subindex CAN_2057_Index1605[] =
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&CAN_2057_highestSubIndex_obj1605 }
                     };

/* index 0x1606 :   Receive PDO 7 Mapping. */
                    UNS8 CAN_2057_highestSubIndex_obj1606 = 0; /* number of subindex - 1*/
                    UNS32 CAN_2057_obj1606[] =
                    {
                    };
                    subindex CAN_2057_Index1606[] =
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&CAN_2057_highestSubIndex_obj1606 }
                     };

/* index 0x1607 :   Receive PDO 8 Mapping. */
                    UNS8 CAN_2057_highestSubIndex_obj1607 = 0; /* number of subindex - 1*/
                    UNS32 CAN_2057_obj1607[] =
                    {
                    };
                    subindex CAN_2057_Index1607[] =
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&CAN_2057_highestSubIndex_obj1607 }
                     };

/* index 0x1608 :   Receive PDO 9 Mapping. */
                    UNS8 CAN_2057_highestSubIndex_obj1608 = 0; /* number of subindex - 1*/
                    UNS32 CAN_2057_obj1608[] =
                    {
                    };
                    subindex CAN_2057_Index1608[] =
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&CAN_2057_highestSubIndex_obj1608 }
                     };

/* index 0x1609 :   Receive PDO 10 Mapping. */
                    UNS8 CAN_2057_highestSubIndex_obj1609 = 0; /* number of subindex - 1*/
                    UNS32 CAN_2057_obj1609[] =
                    {
                    };
                    subindex CAN_2057_Index1609[] =
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&CAN_2057_highestSubIndex_obj1609 }
                     };

/* index 0x1800 :   Transmit PDO 1 Parameter. */
                    UNS8 CAN_2057_highestSubIndex_obj1800 = 5; /* number of subindex - 1*/
                    UNS32 CAN_2057_obj1800_COB_ID_used_by_PDO = 0x180;	/* 384 */
                    UNS8 CAN_2057_obj1800_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 CAN_2057_obj1800_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 CAN_2057_obj1800_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 CAN_2057_obj1800_Event_Timer = 0x0;	/* 0 */
                    ODCallback_t CAN_2057_Index1800_callbacks[] =
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex CAN_2057_Index1800[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CAN_2057_highestSubIndex_obj1800 },
                       { RW, uint32, sizeof (UNS32), (void*)&CAN_2057_obj1800_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&CAN_2057_obj1800_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&CAN_2057_obj1800_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&CAN_2057_obj1800_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&CAN_2057_obj1800_Event_Timer }
                     };

/* index 0x1801 :   Transmit PDO 2 Parameter. */
                    UNS8 CAN_2057_highestSubIndex_obj1801 = 5; /* number of subindex - 1*/
                    UNS32 CAN_2057_obj1801_COB_ID_used_by_PDO = 0x280;	/* 640 */
                    UNS8 CAN_2057_obj1801_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 CAN_2057_obj1801_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 CAN_2057_obj1801_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 CAN_2057_obj1801_Event_Timer = 0x0;	/* 0 */
                    ODCallback_t CAN_2057_Index1801_callbacks[] =
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex CAN_2057_Index1801[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CAN_2057_highestSubIndex_obj1801 },
                       { RW, uint32, sizeof (UNS32), (void*)&CAN_2057_obj1801_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&CAN_2057_obj1801_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&CAN_2057_obj1801_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&CAN_2057_obj1801_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&CAN_2057_obj1801_Event_Timer }
                     };

/* index 0x1802 :   Transmit PDO 3 Parameter. */
                    UNS8 CAN_2057_highestSubIndex_obj1802 = 5; /* number of subindex - 1*/
                    UNS32 CAN_2057_obj1802_COB_ID_used_by_PDO = 0x380;	/* 896 */
                    UNS8 CAN_2057_obj1802_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 CAN_2057_obj1802_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 CAN_2057_obj1802_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 CAN_2057_obj1802_Event_Timer = 0x0;	/* 0 */
                    ODCallback_t CAN_2057_Index1802_callbacks[] =
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex CAN_2057_Index1802[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CAN_2057_highestSubIndex_obj1802 },
                       { RW, uint32, sizeof (UNS32), (void*)&CAN_2057_obj1802_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&CAN_2057_obj1802_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&CAN_2057_obj1802_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&CAN_2057_obj1802_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&CAN_2057_obj1802_Event_Timer }
                     };

/* index 0x1803 :   Transmit PDO 4 Parameter. */
                    UNS8 CAN_2057_highestSubIndex_obj1803 = 5; /* number of subindex - 1*/
                    UNS32 CAN_2057_obj1803_COB_ID_used_by_PDO = 0x480;	/* 1152 */
                    UNS8 CAN_2057_obj1803_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 CAN_2057_obj1803_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 CAN_2057_obj1803_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 CAN_2057_obj1803_Event_Timer = 0x0;	/* 0 */
                    ODCallback_t CAN_2057_Index1803_callbacks[] =
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex CAN_2057_Index1803[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CAN_2057_highestSubIndex_obj1803 },
                       { RW, uint32, sizeof (UNS32), (void*)&CAN_2057_obj1803_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&CAN_2057_obj1803_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&CAN_2057_obj1803_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&CAN_2057_obj1803_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&CAN_2057_obj1803_Event_Timer }
                     };

/* index 0x1804 :   Transmit PDO 5 Parameter. */
                    UNS8 CAN_2057_highestSubIndex_obj1804 = 5; /* number of subindex - 1*/
                    UNS32 CAN_2057_obj1804_COB_ID_used_by_PDO = 0x80000000;	/* 2147483648 */
                    UNS8 CAN_2057_obj1804_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 CAN_2057_obj1804_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 CAN_2057_obj1804_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 CAN_2057_obj1804_Event_Timer = 0x0;	/* 0 */
                    ODCallback_t CAN_2057_Index1804_callbacks[] =
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex CAN_2057_Index1804[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CAN_2057_highestSubIndex_obj1804 },
                       { RW, uint32, sizeof (UNS32), (void*)&CAN_2057_obj1804_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&CAN_2057_obj1804_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&CAN_2057_obj1804_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&CAN_2057_obj1804_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&CAN_2057_obj1804_Event_Timer }
                     };

/* index 0x1805 :   Transmit PDO 6 Parameter. */
                    UNS8 CAN_2057_highestSubIndex_obj1805 = 5; /* number of subindex - 1*/
                    UNS32 CAN_2057_obj1805_COB_ID_used_by_PDO = 0x80000000;	/* 2147483648 */
                    UNS8 CAN_2057_obj1805_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 CAN_2057_obj1805_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 CAN_2057_obj1805_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 CAN_2057_obj1805_Event_Timer = 0x0;	/* 0 */
                    ODCallback_t CAN_2057_Index1805_callbacks[] =
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex CAN_2057_Index1805[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CAN_2057_highestSubIndex_obj1805 },
                       { RW, uint32, sizeof (UNS32), (void*)&CAN_2057_obj1805_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&CAN_2057_obj1805_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&CAN_2057_obj1805_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&CAN_2057_obj1805_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&CAN_2057_obj1805_Event_Timer }
                     };

/* index 0x1806 :   Transmit PDO 7 Parameter. */
                    UNS8 CAN_2057_highestSubIndex_obj1806 = 5; /* number of subindex - 1*/
                    UNS32 CAN_2057_obj1806_COB_ID_used_by_PDO = 0x80000000;	/* 2147483648 */
                    UNS8 CAN_2057_obj1806_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 CAN_2057_obj1806_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 CAN_2057_obj1806_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 CAN_2057_obj1806_Event_Timer = 0x0;	/* 0 */
                    ODCallback_t CAN_2057_Index1806_callbacks[] =
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex CAN_2057_Index1806[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CAN_2057_highestSubIndex_obj1806 },
                       { RW, uint32, sizeof (UNS32), (void*)&CAN_2057_obj1806_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&CAN_2057_obj1806_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&CAN_2057_obj1806_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&CAN_2057_obj1806_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&CAN_2057_obj1806_Event_Timer }
                     };

/* index 0x1807 :   Transmit PDO 8 Parameter. */
                    UNS8 CAN_2057_highestSubIndex_obj1807 = 5; /* number of subindex - 1*/
                    UNS32 CAN_2057_obj1807_COB_ID_used_by_PDO = 0x80000000;	/* 2147483648 */
                    UNS8 CAN_2057_obj1807_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 CAN_2057_obj1807_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 CAN_2057_obj1807_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 CAN_2057_obj1807_Event_Timer = 0x0;	/* 0 */
                    ODCallback_t CAN_2057_Index1807_callbacks[] =
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex CAN_2057_Index1807[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CAN_2057_highestSubIndex_obj1807 },
                       { RW, uint32, sizeof (UNS32), (void*)&CAN_2057_obj1807_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&CAN_2057_obj1807_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&CAN_2057_obj1807_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&CAN_2057_obj1807_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&CAN_2057_obj1807_Event_Timer }
                     };

/* index 0x1808 :   Transmit PDO 9 Parameter. */
                    UNS8 CAN_2057_highestSubIndex_obj1808 = 5; /* number of subindex - 1*/
                    UNS32 CAN_2057_obj1808_COB_ID_used_by_PDO = 0x80000000;	/* 2147483648 */
                    UNS8 CAN_2057_obj1808_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 CAN_2057_obj1808_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 CAN_2057_obj1808_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 CAN_2057_obj1808_Event_Timer = 0x0;	/* 0 */
                    ODCallback_t CAN_2057_Index1808_callbacks[] =
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex CAN_2057_Index1808[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CAN_2057_highestSubIndex_obj1808 },
                       { RW, uint32, sizeof (UNS32), (void*)&CAN_2057_obj1808_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&CAN_2057_obj1808_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&CAN_2057_obj1808_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&CAN_2057_obj1808_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&CAN_2057_obj1808_Event_Timer }
                     };

/* index 0x1809 :   Transmit PDO 10 Parameter. */
                    UNS8 CAN_2057_highestSubIndex_obj1809 = 5; /* number of subindex - 1*/
                    UNS32 CAN_2057_obj1809_COB_ID_used_by_PDO = 0x80000000;	/* 2147483648 */
                    UNS8 CAN_2057_obj1809_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 CAN_2057_obj1809_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 CAN_2057_obj1809_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 CAN_2057_obj1809_Event_Timer = 0x0;	/* 0 */
                    ODCallback_t CAN_2057_Index1809_callbacks[] =
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex CAN_2057_Index1809[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CAN_2057_highestSubIndex_obj1809 },
                       { RW, uint32, sizeof (UNS32), (void*)&CAN_2057_obj1809_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&CAN_2057_obj1809_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&CAN_2057_obj1809_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&CAN_2057_obj1809_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&CAN_2057_obj1809_Event_Timer }
                     };

/* index 0x1A00 :   Transmit PDO 1 Mapping. */
                    UNS8 CAN_2057_highestSubIndex_obj1A00 = 0; /* number of subindex - 1*/
                    UNS32 CAN_2057_obj1A00[] =
                    {
                    };
                    subindex CAN_2057_Index1A00[] =
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&CAN_2057_highestSubIndex_obj1A00 }
                     };

/* index 0x1A01 :   Transmit PDO 2 Mapping. */
                    UNS8 CAN_2057_highestSubIndex_obj1A01 = 0; /* number of subindex - 1*/
                    UNS32 CAN_2057_obj1A01[] =
                    {
                    };
                    subindex CAN_2057_Index1A01[] =
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&CAN_2057_highestSubIndex_obj1A01 }
                     };

/* index 0x1A02 :   Transmit PDO 3 Mapping. */
                    UNS8 CAN_2057_highestSubIndex_obj1A02 = 0; /* number of subindex - 1*/
                    UNS32 CAN_2057_obj1A02[] =
                    {
                    };
                    subindex CAN_2057_Index1A02[] =
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&CAN_2057_highestSubIndex_obj1A02 }
                     };

/* index 0x1A03 :   Transmit PDO 4 Mapping. */
                    UNS8 CAN_2057_highestSubIndex_obj1A03 = 0; /* number of subindex - 1*/
                    UNS32 CAN_2057_obj1A03[] =
                    {
                    };
                    subindex CAN_2057_Index1A03[] =
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&CAN_2057_highestSubIndex_obj1A03 }
                     };

/* index 0x1A04 :   Transmit PDO 5 Mapping. */
                    UNS8 CAN_2057_highestSubIndex_obj1A04 = 0; /* number of subindex - 1*/
                    UNS32 CAN_2057_obj1A04[] =
                    {
                    };
                    subindex CAN_2057_Index1A04[] =
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&CAN_2057_highestSubIndex_obj1A04 }
                     };

/* index 0x1A05 :   Transmit PDO 6 Mapping. */
                    UNS8 CAN_2057_highestSubIndex_obj1A05 = 0; /* number of subindex - 1*/
                    UNS32 CAN_2057_obj1A05[] =
                    {
                    };
                    subindex CAN_2057_Index1A05[] =
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&CAN_2057_highestSubIndex_obj1A05 }
                     };

/* index 0x1A06 :   Transmit PDO 7 Mapping. */
                    UNS8 CAN_2057_highestSubIndex_obj1A06 = 0; /* number of subindex - 1*/
                    UNS32 CAN_2057_obj1A06[] =
                    {
                    };
                    subindex CAN_2057_Index1A06[] =
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&CAN_2057_highestSubIndex_obj1A06 }
                     };

/* index 0x1A07 :   Transmit PDO 8 Mapping. */
                    UNS8 CAN_2057_highestSubIndex_obj1A07 = 0; /* number of subindex - 1*/
                    UNS32 CAN_2057_obj1A07[] =
                    {
                    };
                    subindex CAN_2057_Index1A07[] =
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&CAN_2057_highestSubIndex_obj1A07 }
                     };

/* index 0x1A08 :   Transmit PDO 9 Mapping. */
                    UNS8 CAN_2057_highestSubIndex_obj1A08 = 0; /* number of subindex - 1*/
                    UNS32 CAN_2057_obj1A08[] =
                    {
                    };
                    subindex CAN_2057_Index1A08[] =
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&CAN_2057_highestSubIndex_obj1A08 }
                     };

/* index 0x1A09 :   Transmit PDO 10 Mapping. */
                    UNS8 CAN_2057_highestSubIndex_obj1A09 = 0; /* number of subindex - 1*/
                    UNS32 CAN_2057_obj1A09[] =
                    {
                    };
                    subindex CAN_2057_Index1A09[] =
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&CAN_2057_highestSubIndex_obj1A09 }
                     };

/* index 0x2010 :   Mapped variable Power On Value of CAN-2000C Module */
                    UNS8 CAN_2057_highestSubIndex_obj2010 = 2; /* number of subindex - 1*/
                    subindex CAN_2057_Index2010[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CAN_2057_highestSubIndex_obj2010 },
                       { RW, uint8, sizeof (UNS8), (void*)&Power_On_Value_of_CAN_2000C_Module_Power_On_Value_of_1h_to_8h },
                       { RW, uint8, sizeof (UNS8), (void*)&Power_On_Value_of_CAN_2000C_Module_Power_On_Value_of_9h_to_15h }
                     };

/* index 0x6200 :   Mapped variable Write Outputs 8 Bit */
                    UNS8 CAN_2057_highestSubIndex_obj6200 = 2; /* number of subindex - 1*/
                    subindex CAN_2057_Index6200[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CAN_2057_highestSubIndex_obj6200 },
                       { RW, uint8, sizeof (UNS8), (void*)&Write_Outputs_8_Bit[0] },
                       { RW, uint8, sizeof (UNS8), (void*)&Write_Outputs_8_Bit[1] }
                     };

/* index 0x6202 :   Mapped variable Change Polarity Outputs 8 Bit */
                    UNS8 CAN_2057_highestSubIndex_obj6202 = 2; /* number of subindex - 1*/
                    subindex CAN_2057_Index6202[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CAN_2057_highestSubIndex_obj6202 },
                       { RW, uint8, sizeof (UNS8), (void*)&Change_Polarity_Outputs_8_Bit[0] },
                       { RW, uint8, sizeof (UNS8), (void*)&Change_Polarity_Outputs_8_Bit[1] }
                     };

/* index 0x6206 :   Mapped variable Error Mode Outputs 8 Bit */
                    UNS8 CAN_2057_highestSubIndex_obj6206 = 2; /* number of subindex - 1*/
                    subindex CAN_2057_Index6206[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CAN_2057_highestSubIndex_obj6206 },
                       { RW, uint8, sizeof (UNS8), (void*)&Error_Mode_Outputs_8_Bit[0] },
                       { RW, uint8, sizeof (UNS8), (void*)&Error_Mode_Outputs_8_Bit[1] }
                     };

/* index 0x6207 :   Mapped variable Error Value Outputs 8 Bit */
                    UNS8 CAN_2057_highestSubIndex_obj6207 = 2; /* number of subindex - 1*/
                    subindex CAN_2057_Index6207[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&CAN_2057_highestSubIndex_obj6207 },
                       { RW, uint8, sizeof (UNS8), (void*)&Error_Value_Outputs_8_Bit[0] },
                       { RW, uint8, sizeof (UNS8), (void*)&Error_Value_Outputs_8_Bit[1] }
                     };

/**************************************************************************/
/* Declaration of pointed variables                                       */
/**************************************************************************/

const indextable CAN_2057_objdict[] =
{
  { (subindex*)CAN_2057_Index1000,sizeof(CAN_2057_Index1000)/sizeof(CAN_2057_Index1000[0]), 0x1000},
  { (subindex*)CAN_2057_Index1001,sizeof(CAN_2057_Index1001)/sizeof(CAN_2057_Index1001[0]), 0x1001},
  { (subindex*)CAN_2057_Index1003,sizeof(CAN_2057_Index1003)/sizeof(CAN_2057_Index1003[0]), 0x1003},
  { (subindex*)CAN_2057_Index1005,sizeof(CAN_2057_Index1005)/sizeof(CAN_2057_Index1005[0]), 0x1005},
  { (subindex*)CAN_2057_Index1008,sizeof(CAN_2057_Index1008)/sizeof(CAN_2057_Index1008[0]), 0x1008},
  { (subindex*)CAN_2057_Index1009,sizeof(CAN_2057_Index1009)/sizeof(CAN_2057_Index1009[0]), 0x1009},
  { (subindex*)CAN_2057_Index100A,sizeof(CAN_2057_Index100A)/sizeof(CAN_2057_Index100A[0]), 0x100A},
  { (subindex*)CAN_2057_Index100C,sizeof(CAN_2057_Index100C)/sizeof(CAN_2057_Index100C[0]), 0x100C},
  { (subindex*)CAN_2057_Index100D,sizeof(CAN_2057_Index100D)/sizeof(CAN_2057_Index100D[0]), 0x100D},
  { (subindex*)CAN_2057_Index1010,sizeof(CAN_2057_Index1010)/sizeof(CAN_2057_Index1010[0]), 0x1010},
  { (subindex*)CAN_2057_Index1011,sizeof(CAN_2057_Index1011)/sizeof(CAN_2057_Index1011[0]), 0x1011},
  { (subindex*)CAN_2057_Index1014,sizeof(CAN_2057_Index1014)/sizeof(CAN_2057_Index1014[0]), 0x1014},
  { (subindex*)CAN_2057_Index1017,sizeof(CAN_2057_Index1017)/sizeof(CAN_2057_Index1017[0]), 0x1017},
  { (subindex*)CAN_2057_Index1018,sizeof(CAN_2057_Index1018)/sizeof(CAN_2057_Index1018[0]), 0x1018},
  { (subindex*)CAN_2057_Index1200,sizeof(CAN_2057_Index1200)/sizeof(CAN_2057_Index1200[0]), 0x1200},
  { (subindex*)CAN_2057_Index1400,sizeof(CAN_2057_Index1400)/sizeof(CAN_2057_Index1400[0]), 0x1400},
  { (subindex*)CAN_2057_Index1401,sizeof(CAN_2057_Index1401)/sizeof(CAN_2057_Index1401[0]), 0x1401},
  { (subindex*)CAN_2057_Index1402,sizeof(CAN_2057_Index1402)/sizeof(CAN_2057_Index1402[0]), 0x1402},
  { (subindex*)CAN_2057_Index1403,sizeof(CAN_2057_Index1403)/sizeof(CAN_2057_Index1403[0]), 0x1403},
  { (subindex*)CAN_2057_Index1404,sizeof(CAN_2057_Index1404)/sizeof(CAN_2057_Index1404[0]), 0x1404},
  { (subindex*)CAN_2057_Index1405,sizeof(CAN_2057_Index1405)/sizeof(CAN_2057_Index1405[0]), 0x1405},
  { (subindex*)CAN_2057_Index1406,sizeof(CAN_2057_Index1406)/sizeof(CAN_2057_Index1406[0]), 0x1406},
  { (subindex*)CAN_2057_Index1407,sizeof(CAN_2057_Index1407)/sizeof(CAN_2057_Index1407[0]), 0x1407},
  { (subindex*)CAN_2057_Index1408,sizeof(CAN_2057_Index1408)/sizeof(CAN_2057_Index1408[0]), 0x1408},
  { (subindex*)CAN_2057_Index1409,sizeof(CAN_2057_Index1409)/sizeof(CAN_2057_Index1409[0]), 0x1409},
  { (subindex*)CAN_2057_Index1600,sizeof(CAN_2057_Index1600)/sizeof(CAN_2057_Index1600[0]), 0x1600},
  { (subindex*)CAN_2057_Index1601,sizeof(CAN_2057_Index1601)/sizeof(CAN_2057_Index1601[0]), 0x1601},
  { (subindex*)CAN_2057_Index1602,sizeof(CAN_2057_Index1602)/sizeof(CAN_2057_Index1602[0]), 0x1602},
  { (subindex*)CAN_2057_Index1603,sizeof(CAN_2057_Index1603)/sizeof(CAN_2057_Index1603[0]), 0x1603},
  { (subindex*)CAN_2057_Index1604,sizeof(CAN_2057_Index1604)/sizeof(CAN_2057_Index1604[0]), 0x1604},
  { (subindex*)CAN_2057_Index1605,sizeof(CAN_2057_Index1605)/sizeof(CAN_2057_Index1605[0]), 0x1605},
  { (subindex*)CAN_2057_Index1606,sizeof(CAN_2057_Index1606)/sizeof(CAN_2057_Index1606[0]), 0x1606},
  { (subindex*)CAN_2057_Index1607,sizeof(CAN_2057_Index1607)/sizeof(CAN_2057_Index1607[0]), 0x1607},
  { (subindex*)CAN_2057_Index1608,sizeof(CAN_2057_Index1608)/sizeof(CAN_2057_Index1608[0]), 0x1608},
  { (subindex*)CAN_2057_Index1609,sizeof(CAN_2057_Index1609)/sizeof(CAN_2057_Index1609[0]), 0x1609},
  { (subindex*)CAN_2057_Index1800,sizeof(CAN_2057_Index1800)/sizeof(CAN_2057_Index1800[0]), 0x1800},
  { (subindex*)CAN_2057_Index1801,sizeof(CAN_2057_Index1801)/sizeof(CAN_2057_Index1801[0]), 0x1801},
  { (subindex*)CAN_2057_Index1802,sizeof(CAN_2057_Index1802)/sizeof(CAN_2057_Index1802[0]), 0x1802},
  { (subindex*)CAN_2057_Index1803,sizeof(CAN_2057_Index1803)/sizeof(CAN_2057_Index1803[0]), 0x1803},
  { (subindex*)CAN_2057_Index1804,sizeof(CAN_2057_Index1804)/sizeof(CAN_2057_Index1804[0]), 0x1804},
  { (subindex*)CAN_2057_Index1805,sizeof(CAN_2057_Index1805)/sizeof(CAN_2057_Index1805[0]), 0x1805},
  { (subindex*)CAN_2057_Index1806,sizeof(CAN_2057_Index1806)/sizeof(CAN_2057_Index1806[0]), 0x1806},
  { (subindex*)CAN_2057_Index1807,sizeof(CAN_2057_Index1807)/sizeof(CAN_2057_Index1807[0]), 0x1807},
  { (subindex*)CAN_2057_Index1808,sizeof(CAN_2057_Index1808)/sizeof(CAN_2057_Index1808[0]), 0x1808},
  { (subindex*)CAN_2057_Index1809,sizeof(CAN_2057_Index1809)/sizeof(CAN_2057_Index1809[0]), 0x1809},
  { (subindex*)CAN_2057_Index1A00,sizeof(CAN_2057_Index1A00)/sizeof(CAN_2057_Index1A00[0]), 0x1A00},
  { (subindex*)CAN_2057_Index1A01,sizeof(CAN_2057_Index1A01)/sizeof(CAN_2057_Index1A01[0]), 0x1A01},
  { (subindex*)CAN_2057_Index1A02,sizeof(CAN_2057_Index1A02)/sizeof(CAN_2057_Index1A02[0]), 0x1A02},
  { (subindex*)CAN_2057_Index1A03,sizeof(CAN_2057_Index1A03)/sizeof(CAN_2057_Index1A03[0]), 0x1A03},
  { (subindex*)CAN_2057_Index1A04,sizeof(CAN_2057_Index1A04)/sizeof(CAN_2057_Index1A04[0]), 0x1A04},
  { (subindex*)CAN_2057_Index1A05,sizeof(CAN_2057_Index1A05)/sizeof(CAN_2057_Index1A05[0]), 0x1A05},
  { (subindex*)CAN_2057_Index1A06,sizeof(CAN_2057_Index1A06)/sizeof(CAN_2057_Index1A06[0]), 0x1A06},
  { (subindex*)CAN_2057_Index1A07,sizeof(CAN_2057_Index1A07)/sizeof(CAN_2057_Index1A07[0]), 0x1A07},
  { (subindex*)CAN_2057_Index1A08,sizeof(CAN_2057_Index1A08)/sizeof(CAN_2057_Index1A08[0]), 0x1A08},
  { (subindex*)CAN_2057_Index1A09,sizeof(CAN_2057_Index1A09)/sizeof(CAN_2057_Index1A09[0]), 0x1A09},
  { (subindex*)CAN_2057_Index2010,sizeof(CAN_2057_Index2010)/sizeof(CAN_2057_Index2010[0]), 0x2010},
  { (subindex*)CAN_2057_Index6200,sizeof(CAN_2057_Index6200)/sizeof(CAN_2057_Index6200[0]), 0x6200},
  { (subindex*)CAN_2057_Index6202,sizeof(CAN_2057_Index6202)/sizeof(CAN_2057_Index6202[0]), 0x6202},
  { (subindex*)CAN_2057_Index6206,sizeof(CAN_2057_Index6206)/sizeof(CAN_2057_Index6206[0]), 0x6206},
  { (subindex*)CAN_2057_Index6207,sizeof(CAN_2057_Index6207)/sizeof(CAN_2057_Index6207[0]), 0x6207},
};

const indextable * CAN_2057_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks)
{
	int i;
	*callbacks = NULL;
	switch(wIndex){
		case 0x1000: i = 0;break;
		case 0x1001: i = 1;break;
        case 0x1003: i = 2;*callbacks = CAN_2057_Index1003_callbacks; break;
        case 0x1005: i = 3;*callbacks = CAN_2057_Index1005_callbacks; break;
		case 0x1008: i = 4;break;
		case 0x1009: i = 5;break;
		case 0x100A: i = 6;break;
		case 0x100C: i = 7;break;
		case 0x100D: i = 8;break;
		case 0x1010: i = 9;break;
		case 0x1011: i = 10;break;
		case 0x1014: i = 11;break;
        case 0x1017: i = 12;*callbacks = CAN_2057_Index1017_callbacks; break;
		case 0x1018: i = 13;break;
		case 0x1200: i = 14;break;
		case 0x1400: i = 15;break;
		case 0x1401: i = 16;break;
		case 0x1402: i = 17;break;
		case 0x1403: i = 18;break;
		case 0x1404: i = 19;break;
		case 0x1405: i = 20;break;
		case 0x1406: i = 21;break;
		case 0x1407: i = 22;break;
		case 0x1408: i = 23;break;
		case 0x1409: i = 24;break;
		case 0x1600: i = 25;break;
		case 0x1601: i = 26;break;
		case 0x1602: i = 27;break;
		case 0x1603: i = 28;break;
		case 0x1604: i = 29;break;
		case 0x1605: i = 30;break;
		case 0x1606: i = 31;break;
		case 0x1607: i = 32;break;
		case 0x1608: i = 33;break;
		case 0x1609: i = 34;break;
        case 0x1800: i = 35;*callbacks = CAN_2057_Index1800_callbacks; break;
        case 0x1801: i = 36;*callbacks = CAN_2057_Index1801_callbacks; break;
        case 0x1802: i = 37;*callbacks = CAN_2057_Index1802_callbacks; break;
        case 0x1803: i = 38;*callbacks = CAN_2057_Index1803_callbacks; break;
        case 0x1804: i = 39;*callbacks = CAN_2057_Index1804_callbacks; break;
        case 0x1805: i = 40;*callbacks = CAN_2057_Index1805_callbacks; break;
        case 0x1806: i = 41;*callbacks = CAN_2057_Index1806_callbacks; break;
        case 0x1807: i = 42;*callbacks = CAN_2057_Index1807_callbacks; break;
        case 0x1808: i = 43;*callbacks = CAN_2057_Index1808_callbacks; break;
        case 0x1809: i = 44;*callbacks = CAN_2057_Index1809_callbacks; break;
		case 0x1A00: i = 45;break;
		case 0x1A01: i = 46;break;
		case 0x1A02: i = 47;break;
		case 0x1A03: i = 48;break;
		case 0x1A04: i = 49;break;
		case 0x1A05: i = 50;break;
		case 0x1A06: i = 51;break;
		case 0x1A07: i = 52;break;
		case 0x1A08: i = 53;break;
		case 0x1A09: i = 54;break;
		case 0x2010: i = 55;break;
		case 0x6200: i = 56;break;
		case 0x6202: i = 57;break;
		case 0x6206: i = 58;break;
		case 0x6207: i = 59;break;
		default:
			*errorCode = OD_NO_SUCH_OBJECT;
			return NULL;
	}
	*errorCode = OD_SUCCESSFUL;
    return &CAN_2057_objdict[i];
}

/* 
 * To count at which received SYNC a PDO must be sent.
 * Even if no pdoTransmit are defined, at least one entry is computed
 * for compilations issues.
 */
s_PDO_status CAN_2057_PDO_status[10] = {s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer};

const quick_index CAN_2057_firstIndex = {
  14, /* SDO_SVR */
  0, /* SDO_CLT */
  15, /* PDO_RCV */
  25, /* PDO_RCV_MAP */
  35, /* PDO_TRS */
  45 /* PDO_TRS_MAP */
};

const quick_index CAN_2057_lastIndex = {
  14, /* SDO_SVR */
  0, /* SDO_CLT */
  24, /* PDO_RCV */
  34, /* PDO_RCV_MAP */
  44, /* PDO_TRS */
  54 /* PDO_TRS_MAP */
};

const UNS16 CAN_2057_ObjdictSize = sizeof(CAN_2057_objdict)/sizeof(CAN_2057_objdict[0]);

CO_Data CAN_2057_Data = CANOPEN_NODE_DATA_INITIALIZER(CAN_2057);

